import type {ContentLesson} from "../../../types.js";
const lesson=(id:string,number:number,title:string,goal:string,explanation:string,items:Array<[string,string,string]>,practices:string[]):ContentLesson=>({id,number,title,goal,minutes:18,explanation,practices,words:items.map(([target,source,example])=>({target,source,example,hint:"Произнесите фразу и используйте её в своём примере"}))});
export const englishCoreLessons:ContentLesson[]=[
 lesson("introductions",1,"Знакомство","Поздороваться и коротко представиться","I am и I'm равнозначны; сокращение естественно в разговоре.",[["Hello!","Привет!","Hello! I'm Alex."],["My name is…","Меня зовут…","My name is Nina."],["Nice to meet you.","Приятно познакомиться.","Nice to meet you, Sam."],["How are you?","Как дела?","Hi! How are you?"],["I'm fine, thanks.","Хорошо, спасибо.","I'm fine, thanks."],["See you later.","До встречи.","See you later, Anna."]],["Карточки","Диалог","Ввод текста","Произношение"]),
 lesson("daily-life",2,"Мой день","Описать основные действия дня","Present Simple описывает привычки. С I используйте базовую форму глагола.",[["I wake up at seven.","Я просыпаюсь в семь.","On weekdays I wake up at seven."],["I have breakfast.","Я завтракаю.","I have breakfast at home."],["I go to work.","Я иду на работу.","I go to work by bus."],["I study English.","Я учу английский.","I study English every day."],["I come home at six.","Я прихожу домой в шесть.","I come home at six."],["I go to bed.","Я ложусь спать.","I go to bed at eleven."]],["Порядок слов","Аудирование","Рассказ","Проверка"]),
 lesson("questions",3,"Простые вопросы","Задать и понять базовый вопрос","В Present Simple вопрос с I/you строится через do: Where do you live?",[["Where do you live?","Где ты живёшь?","Where do you live now?"],["What do you do?","Чем ты занимаешься?","What do you do on weekends?"],["Do you speak English?","Ты говоришь по-английски?","Do you speak English at work?"],["What time is it?","Который час?","Excuse me, what time is it?"],["How much is it?","Сколько это стоит?","How much is this book?"],["Can you help me?","Вы можете мне помочь?","Excuse me, can you help me?"]],["Выбор ответа","Сопоставление","Диалог","Проверка"]),
 lesson("travel",4,"В городе и поездке","Спросить дорогу и купить билет","Could you…? делает просьбу вежливой. После could используется базовая форма глагола.",[["Where is the station?","Где вокзал?","Excuse me, where is the station?"],["A ticket, please.","Билет, пожалуйста.","A ticket to London, please."],["Turn left.","Поверните налево.","Turn left at the bank."],["Turn right.","Поверните направо.","Turn right after the café."],["Is it far?","Это далеко?","Is it far from here?"],["Could you repeat that?","Повторите, пожалуйста.","Could you repeat that more slowly?"]],["Карта","Диалог","Аудирование","Произношение"]),
 lesson("plans",5,"Планы","Предложить встречу и ответить","Let's предлагает совместное действие, а would like выражает вежливое желание.",[["What are you doing tomorrow?","Что ты делаешь завтра?","What are you doing tomorrow evening?"],["Let's meet at six.","Давай встретимся в шесть.","Let's meet at six near the station."],["Would you like some coffee?","Хотите кофе?","Would you like some coffee?"],["That sounds good.","Звучит хорошо.","That sounds good to me."],["Sorry, I can't.","Извините, я не могу.","Sorry, I can't on Friday."],["See you tomorrow.","До завтра.","Great, see you tomorrow."]],["Диалог","Письмо","Ролевая практика","Мини-экзамен"]),
];
