import crypto from "node:crypto";
import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { AiUsageRepository } from "../server/ai/repository";
import { FamilyService } from "../server/families/service";
import { IdentityService } from "../server/identity/service";

const databaseUrl=process.env.TEST_DATABASE_URL;const suite=databaseUrl?describe:describe.skip;
suite("AI usage reservation and tenant isolation",()=>{const pool=new pg.Pool({connectionString:databaseUrl,max:4}),identity=new IdentityService(pool),families=new FamilyService(pool),usage=new AiUsageRepository(pool);const runId=crypto.randomUUID(),password="correct horse ai gateway password";let userA="",userB="",familyA="",familyB="";
  beforeAll(async()=>{userA=(await identity.register({email:`ai-a-${runId}@example.test`,password,displayName:"AI A"})).userId!;userB=(await identity.register({email:`ai-b-${runId}@example.test`,password,displayName:"AI B"})).userId!;for(const id of[userA,userB])await identity.verifyEmail(await identity.issueOneTimeToken(id,"verify_email"));familyA=(await families.createFamily(userA,"AI family A",crypto.randomUUID())).familyId;familyB=(await families.createFamily(userB,"AI family B",crypto.randomUUID())).familyId;const values={aiEnabled:true,allowedModels:["openrouter/gpt-4.1-mini"],monthlyTokenLimit:1000,locale:"ru",timezone:"Europe/Moscow",notificationsEnabled:true,aiHistoryRetentionDays:0};await families.updateSettings({userId:userA,sessionId:crypto.randomUUID(),familyId:familyA,role:"owner"},{version:1,values},crypto.randomUUID());await families.updateSettings({userId:userB,sessionId:crypto.randomUUID(),familyId:familyB,role:"owner"},{version:1,values},crypto.randomUUID());});
  afterAll(()=>pool.end());
  it("reserves, settles actual tokens and never stores prompts",async()=>{const requestId=crypto.randomUUID();expect((await usage.reserve(userA,familyA,requestId,"openrouter/gpt-4.1-mini",800)).providerKey).toBe("openrouter");await usage.settle(userA,familyA,requestId,{promptTokens:100,completionTokens:50,cachedTokens:10,reasoningTokens:0},25,"succeeded");const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id',$2,true)",[userA,familyA]);expect((await client.query("SELECT prompt_tokens,completion_tokens,cost_micros FROM ai.usage_ledger WHERE request_id=$1",[requestId])).rows[0]).toMatchObject({prompt_tokens:"100",completion_tokens:"50"});const columns=(await client.query("SELECT column_name FROM information_schema.columns WHERE table_schema='ai' AND table_name IN ('requests','usage_ledger')")).rows.map(row=>row.column_name);expect(columns).not.toContain("prompt");expect(columns).not.toContain("response");await client.query("ROLLBACK");}finally{client.release();}});
  it("rejects overspend and hides another tenant ledger",async()=>{await expect(usage.reserve(userA,familyA,crypto.randomUUID(),"openrouter/gpt-4.1-mini",951)).rejects.toMatchObject({code:"AI_FAMILY_TOKEN_BUDGET"});const client=await pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id',$2,true)",[userB,familyB]);expect((await client.query("SELECT * FROM ai.usage_ledger WHERE user_id=$1",[userA])).rowCount).toBe(0);await client.query("ROLLBACK");}finally{client.release();}});
});
