import crypto from "node:crypto";
import pg from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { FamilyService } from "../server/families/service";
import { IdentityService } from "../server/identity/service";
import { LearningService } from "../server/learning/service";

const databaseUrl=process.env.TEST_DATABASE_URL;const suite=databaseUrl?describe:describe.skip;
suite("user-owned learning data",()=>{const pool=new pg.Pool({connectionString:databaseUrl,max:4}),identity=new IdentityService(pool),families=new FamilyService(pool),learning=new LearningService(pool);const runId=crypto.randomUUID(),password="correct horse learning password";let userId="",ownerId="",sourceFamily="",targetFamily="";
  beforeAll(async()=>{userId=(await identity.register({email:`learner-${runId}@example.test`,password,displayName:"Ученик"})).userId!;ownerId=(await identity.register({email:`target-${runId}@example.test`,password,displayName:"Владелец"})).userId!;for(const id of[userId,ownerId])await identity.verifyEmail(await identity.issueOneTimeToken(id,"verify_email"));sourceFamily=(await families.createFamily(userId,"Исходная",crypto.randomUUID())).familyId;targetFamily=(await families.createFamily(ownerId,"Целевая",crypto.randomUUID())).familyId;});afterAll(()=>pool.end());
  it("stores deterministic progress, attempts and vocabulary under user_id",async()=>{await learning.enroll(userId,sourceFamily,"italian-a0-a1");expect(await learning.saveProgress(userId,sourceFamily,{courseKey:"italian-a0-a1",lessonKey:"greetings",currentStep:2,completionPercent:25,completed:false,version:0})).toMatchObject({lesson_key:"greetings",version:1});expect(await learning.submitAttempt(userId,sourceFamily,{courseKey:"italian-a0-a1",lessonKey:"greetings",exerciseKey:"word-1",answer:"Ciao"})).toMatchObject({score:100,correct:true});expect((await learning.addVocabulary(userId,sourceFamily,{courseKey:"italian-a0-a1",term:"Ciao",translation:"Привет",lessonKey:"greetings"})).term).toBe("Ciao");});
  it("keeps all learning records when family membership changes",async()=>{const invitation=await families.invite({userId:ownerId,sessionId:crypto.randomUUID(),familyId:targetFamily,role:"owner"},{userId,role:"member"},crypto.randomUUID());await families.transferOwnership({userId,sessionId:crypto.randomUUID(),familyId:sourceFamily,role:"owner"},ownerId,crypto.randomUUID()).catch(()=>undefined);/* no target member in source: sole owner guard is expected */await expect(families.accept(userId,invitation.token,password,crypto.randomUUID())).rejects.toThrow("SOLE_OWNER");
    const helper=(await identity.register({email:`helper-${runId}@example.test`,password,displayName:"Помощник"})).userId!;await identity.verifyEmail(await identity.issueOneTimeToken(helper,"verify_email"));const helperInvite=await families.invite({userId,sessionId:crypto.randomUUID(),familyId:sourceFamily,role:"owner"},{userId:helper,role:"member"},crypto.randomUUID());await families.accept(helper,helperInvite.token,password,crypto.randomUUID());await families.transferOwnership({userId,sessionId:crypto.randomUUID(),familyId:sourceFamily,role:"owner"},helper,crypto.randomUUID());await families.accept(userId,invitation.token,password,crypto.randomUUID());
    expect((await learning.progress(userId,targetFamily))[0]).toMatchObject({lesson_key:"greetings",completion_percent:25});const c=await pool.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id',$2,true)",[ownerId,targetFamily]);expect((await c.query("SELECT count(*)::int n FROM learning.lesson_progress WHERE user_id=$1",[userId])).rows[0].n).toBe(0);await c.query("ROLLBACK");}finally{c.release();}});
});
