import crypto from "node:crypto";
import pg from "pg";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {AdminService} from "../server/admin/service";
import {totp} from "../server/admin/totp";
import {IdentityService,hashOpaqueToken} from "../server/identity/service";

const databaseUrl=process.env.TEST_DATABASE_URL,adminUrl=process.env.TEST_ADMIN_DATABASE_URL;const suite=databaseUrl&&adminUrl?describe:describe.skip;
suite("MFA-protected Super Admin boundary",()=>{const pool=new pg.Pool({connectionString:databaseUrl,max:4}),owner=new pg.Pool({connectionString:adminUrl,max:1}),identity=new IdentityService(pool),admin=new AdminService(pool),runId=crypto.randomUUID(),password="correct horse super admin password";let adminId="",targetId="",secret="",adminToken="";
  beforeAll(async()=>{adminId=(await identity.register({email:`root-${runId}@example.test`,password,displayName:"Root"})).userId!;targetId=(await identity.register({email:`target-${runId}@example.test`,password,displayName:"Target"})).userId!;for(const id of[adminId,targetId])await identity.verifyEmail(await identity.issueOneTimeToken(id,"verify_email"));await owner.query("UPDATE identity.users SET is_super_admin=true WHERE id=$1",[adminId]);const login=await identity.login({email:`root-${runId}@example.test`,password},"test",null);expect(login).not.toBeNull();const enrollment=await admin.beginEnrollment(adminId,password);secret=enrollment.secret;await admin.activate(adminId,totp(secret));adminToken=await admin.verifyAndCreateSession(adminId,login!.sessionId,totp(secret));});afterAll(async()=>{await pool.end();await owner.end();});
  it("requires a valid short MFA session for cross-tenant views",async()=>{expect(await admin.overview(adminToken)).toMatchObject({users:expect.any(Number),families:expect.any(Number)});await expect(pool.query("SELECT admin.overview($1)",[hashOpaqueToken("invalid-admin-token")])).rejects.toThrow("ADMIN_SESSION_REQUIRED");});
  it("requires fresh password and a non-replayed TOTP for dangerous actions",async()=>{await expect(admin.blockUser(adminToken,targetId,true,"security incident",crypto.randomUUID())).rejects.toThrow("ADMIN_SESSION_REQUIRED");await admin.reauthenticate(adminToken,adminId,password,totp(secret,Date.now()+30_000));await admin.blockUser(adminToken,targetId,true,"security incident",crypto.randomUUID());expect((await owner.query("SELECT status FROM identity.users WHERE id=$1",[targetId])).rows[0].status).toBe("blocked");expect((await admin.events(adminToken)).admin.some((event:{action:string})=>event.action==="admin.user.blocked")).toBe(true);});
  it("versions AI prices and provides safe usage aggregates",async()=>{const modelId="00000000-0000-4000-8000-000000000012",before=Number((await owner.query("SELECT count(*) n FROM ai.price_versions WHERE model_id=$1",[modelId])).rows[0].n);await admin.setModelPrice(adminToken,modelId,{promptMicrosPerMillion:400000,completionMicrosPerMillion:1600000,currency:"USD",reason:"scheduled tariff refresh"},crypto.randomUUID());const prices=await owner.query("SELECT effective_to FROM ai.price_versions WHERE model_id=$1 ORDER BY effective_from",[modelId]);expect(prices.rowCount).toBe(before+1);expect(prices.rows.filter(row=>row.effective_to===null)).toHaveLength(1);expect(await admin.usageReport(adminToken)).toMatchObject({byModel:expect.any(Array),byFamily:expect.any(Array),byUser:expect.any(Array)});});
});
