import crypto from "node:crypto";
import express from "express";
import rateLimit from "express-rate-limit";
import type pg from "pg";
import { z } from "zod";
import { adminFeatureFlagSchema,adminMfaActivateSchema,adminMfaEnrollSchema,adminMfaVerifySchema,adminModelMutationSchema,adminPriceMutationSchema,adminReauthSchema,adminRevokeSessionsSchema,adminUserMutationSchema } from "../../shared/admin-schemas.js";
import { config } from "../config.js";
import { AdminService } from "./service.js";

const SESSION_COOKIE="lt_session",ADMIN_COOKIE="lt_admin",adminCookie={httpOnly:true,secure:config.secureCookies,sameSite:"strict" as const,path:"/api/v1/admin",maxAge:Math.min(Math.max(config.adminSessionMinutes,1),15)*60_000};
const limiter=rateLimit({windowMs:60_000,limit:60,standardHeaders:true,legacyHeaders:false}),mfaLimiter=rateLimit({windowMs:15*60_000,limit:10,standardHeaders:true,legacyHeaders:false});
function safeError(error:unknown){const message=error instanceof Error?error.message:"ADMIN_OPERATION_FAILED";for(const code of["MFA_ENROLLMENT_REQUIRED","INVALID_MFA_CODE","MFA_REQUIRED","REAUTH_FAILED","ADMIN_SESSION_REQUIRED","ADMIN_SELF_MUTATION_FORBIDDEN","ADMIN_REASON_REQUIRED","USER_NOT_FOUND","MODEL_NOT_FOUND","VERSION_CONFLICT"])if(message.includes(code))return code;return"ADMIN_OPERATION_FAILED";}
export function createAdminRouter(pool:pg.Pool){const router=express.Router(),service=new AdminService(pool);router.use(limiter);router.use((req,res,next)=>{if(!config.secureCookies||req.method==="GET"||req.get("origin")===new URL(config.appUrl).origin)return next();return res.status(403).json({error:{code:"INVALID_ORIGIN",message:"Источник запроса не разрешён"}});});
  const principal:express.RequestHandler=async(req,res,next)=>{const session=req.cookies?.[SESSION_COOKIE] as string|undefined,actor=session?await service.principal(session):null;if(!actor)return res.status(404).json({error:{code:"NOT_FOUND",message:"Страница не найдена"}});res.locals.principal=actor;next();};
  router.get("/mfa/status",principal,async(_req,res)=>res.json(await service.mfaStatus(res.locals.principal.userId)));
  router.post("/mfa/enroll",mfaLimiter,principal,async(req,res)=>{try{res.json(await service.beginEnrollment(res.locals.principal.userId,adminMfaEnrollSchema.parse(req.body).password));}catch(error){const code=safeError(error);res.status(401).json({error:{code,message:"Не удалось начать настройку MFA"}});}});
  router.post("/mfa/activate",mfaLimiter,principal,async(req,res)=>{try{await service.activate(res.locals.principal.userId,adminMfaActivateSchema.parse(req.body).code);res.json({status:"enabled"});}catch(error){const code=safeError(error);res.status(400).json({error:{code,message:"Код MFA не принят"}});}});
  router.post("/session",mfaLimiter,principal,async(req,res)=>{try{const token=await service.verifyAndCreateSession(res.locals.principal.userId,res.locals.principal.parentSessionId,adminMfaVerifySchema.parse(req.body).code);res.cookie(ADMIN_COOKIE,token,adminCookie).json({status:"verified",expiresInMinutes:Math.min(Math.max(config.adminSessionMinutes,1),15)});}catch(error){const code=safeError(error);res.status(401).json({error:{code,message:"Код MFA не принят"}});}});
  const admin:express.RequestHandler=async(req,res,next)=>{const token=req.cookies?.[ADMIN_COOKIE] as string|undefined,actor=token?await service.authenticateAdmin(token):null;if(!actor)return res.status(401).json({error:{code:"ADMIN_SESSION_REQUIRED",message:"Требуется подтверждение MFA"}});res.locals.admin={...actor,token};next();};
  router.post("/reauth",mfaLimiter,admin,async(req,res)=>{try{const input=adminReauthSchema.parse(req.body);await service.reauthenticate(res.locals.admin.token,res.locals.admin.user_id,input.password,input.code);res.json({status:"confirmed",validForSeconds:120});}catch(error){if(error instanceof z.ZodError)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"Некорректные данные запроса"}});const code=safeError(error);res.status(401).json({error:{code,message:"Повторное подтверждение не пройдено"}});}});
  router.get("/overview",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.overview(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.overview.read","success",id);res.setHeader("X-Request-Id",id).json(data);});
  router.get("/users",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.users(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.users.read","success",id);res.setHeader("X-Request-Id",id).json({users:data});});
  router.get("/families",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.families(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.families.read","success",id);res.setHeader("X-Request-Id",id).json({families:data});});
  router.get("/ai",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.aiCatalog(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.ai.read","success",id);res.setHeader("X-Request-Id",id).json(data);});
  router.get("/usage",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.usageReport(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.usage.read","success",id);res.setHeader("X-Request-Id",id).json(data);});
  router.get("/system",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.systemStatus(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.system.read","success",id);res.setHeader("X-Request-Id",id).json(data);});
  router.get("/events",admin,async(_req,res)=>{const id=crypto.randomUUID(),data=await service.events(res.locals.admin.token);await service.record(res.locals.admin.token,"admin.events.read","success",id);res.setHeader("X-Request-Id",id).json(data);});
  router.get("/feature-flags",admin,async(_req,res)=>res.json({flags:await service.flags(res.locals.admin.token)}));
  router.put("/users/:id/status",admin,async(req,res)=>{const input=adminUserMutationSchema.parse(req.body),target=z.string().uuid().parse(req.params.id),id=crypto.randomUUID();await service.blockUser(res.locals.admin.token,target,input.blocked,input.reason,id);res.setHeader("X-Request-Id",id).json({status:input.blocked?"blocked":"active"});});
  router.post("/users/:id/revoke-sessions",admin,async(req,res)=>{const input=adminRevokeSessionsSchema.parse(req.body),target=z.string().uuid().parse(req.params.id),id=crypto.randomUUID();await service.revokeSessions(res.locals.admin.token,target,input.reason,id);res.setHeader("X-Request-Id",id).status(204).end();});
  router.put("/ai/models/:id",admin,async(req,res)=>{const input=adminModelMutationSchema.parse(req.body),target=z.string().uuid().parse(req.params.id),id=crypto.randomUUID();await service.setModelEnabled(res.locals.admin.token,target,input.enabled,input.reason,id);res.setHeader("X-Request-Id",id).json({enabled:input.enabled});});
  router.put("/ai/providers/:id",admin,async(req,res)=>{const input=adminModelMutationSchema.parse(req.body),target=z.string().uuid().parse(req.params.id),id=crypto.randomUUID();await service.setProviderEnabled(res.locals.admin.token,target,input.enabled,input.reason,id);res.setHeader("X-Request-Id",id).json({enabled:input.enabled});});
  router.post("/ai/models/:id/prices",admin,async(req,res)=>{const input=adminPriceMutationSchema.parse(req.body),target=z.string().uuid().parse(req.params.id),id=crypto.randomUUID(),result=await service.setModelPrice(res.locals.admin.token,target,input,id);res.setHeader("X-Request-Id",id).status(201).json(result);});
  router.put("/feature-flags/:key",admin,async(req,res)=>{const input=adminFeatureFlagSchema.parse({...req.body,key:req.params.key}),id=crypto.randomUUID(),result=await service.setFlag(res.locals.admin.token,input,id);res.setHeader("X-Request-Id",id).json(result);});
  router.delete("/session",admin,async(_req,res)=>res.clearCookie(ADMIN_COOKIE,adminCookie).status(204).end());return router;}
