import crypto from "node:crypto";
import argon2 from "argon2";
import type pg from "pg";
import { config } from "../config.js";
import { hashOpaqueToken,IdentityService } from "../identity/service.js";
import { decryptMfaSecret,encryptMfaSecret } from "./crypto.js";
import { base32Encode,verifyTotp } from "./totp.js";

const ADMIN_TTL_MAX_MS=15*60_000;
type SecretRow={secret_ciphertext:Buffer;secret_nonce:Buffer;secret_tag:Buffer;key_version:number;last_used_step?:string|null};
export class AdminService{
  private readonly identity:IdentityService;
  constructor(private readonly pool:pg.Pool){this.identity=new IdentityService(pool);}
  async principal(sessionToken:string){const session=await this.identity.authenticate(sessionToken);if(!session)return null;const allowed=await this.pool.query<{allowed:boolean}>("SELECT admin.is_super_admin($1) allowed",[session.user_id]);return allowed.rows[0]?.allowed?{userId:session.user_id,parentSessionId:session.session_id}:null;}
  async mfaStatus(userId:string){return this.withUser(userId,async client=>({enabled:Boolean((await client.query("SELECT 1 FROM admin.mfa_methods WHERE user_id=$1",[userId])).rowCount),pending:Boolean((await client.query("SELECT 1 FROM admin.mfa_enrollments WHERE user_id=$1 AND expires_at>now()",[userId])).rowCount)}));}
  async beginEnrollment(userId:string,password:string){await this.verifyPassword(userId,password);const secret=base32Encode(crypto.randomBytes(20)),encrypted=encryptMfaSecret(secret);const email=await this.withUser(userId,async client=>{await client.query("INSERT INTO admin.mfa_enrollments(user_id,secret_ciphertext,secret_nonce,secret_tag,key_version,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '10 minutes') ON CONFLICT(user_id) DO UPDATE SET secret_ciphertext=excluded.secret_ciphertext,secret_nonce=excluded.secret_nonce,secret_tag=excluded.secret_tag,key_version=excluded.key_version,expires_at=excluded.expires_at,created_at=now()",[userId,encrypted.ciphertext,encrypted.nonce,encrypted.tag,encrypted.keyVersion]);return(await client.query<{email_display:string}>("SELECT email_display FROM identity.user_emails WHERE user_id=$1",[userId])).rows[0]?.email_display??userId;});const issuer="LangTutor";return{secret,otpauthUrl:`otpauth://totp/${encodeURIComponent(issuer)}:${encodeURIComponent(email)}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30`,expiresInSeconds:600};}
  async activate(userId:string,code:string){return this.withUser(userId,async client=>{const row=(await client.query<SecretRow>("SELECT secret_ciphertext,secret_nonce,secret_tag,key_version FROM admin.mfa_enrollments WHERE user_id=$1 AND expires_at>now() FOR UPDATE",[userId])).rows[0];if(!row)throw new Error("MFA_ENROLLMENT_REQUIRED");if(verifyTotp(decryptMfaSecret(row),code)===null)throw new Error("INVALID_MFA_CODE");await client.query("INSERT INTO admin.mfa_methods(user_id,secret_ciphertext,secret_nonce,secret_tag,key_version,last_used_step) VALUES($1,$2,$3,$4,$5,NULL) ON CONFLICT(user_id) DO UPDATE SET secret_ciphertext=excluded.secret_ciphertext,secret_nonce=excluded.secret_nonce,secret_tag=excluded.secret_tag,key_version=excluded.key_version,last_used_step=NULL,enabled_at=now(),updated_at=now()",[userId,row.secret_ciphertext,row.secret_nonce,row.secret_tag,row.key_version]);await client.query("DELETE FROM admin.mfa_enrollments WHERE user_id=$1",[userId]);return true;});}
  async verifyAndCreateSession(userId:string,parentSessionId:string,code:string){const token=crypto.randomBytes(32).toString("base64url");await this.withUser(userId,async client=>{const row=(await client.query<SecretRow>("SELECT secret_ciphertext,secret_nonce,secret_tag,key_version,last_used_step FROM admin.mfa_methods WHERE user_id=$1 FOR UPDATE",[userId])).rows[0];if(!row)throw new Error("MFA_REQUIRED");const step=verifyTotp(decryptMfaSecret(row),code);if(step===null||BigInt(row.last_used_step??-1)>=BigInt(step))throw new Error("INVALID_MFA_CODE");await client.query("UPDATE admin.mfa_methods SET last_used_step=$2,updated_at=now() WHERE user_id=$1",[userId,step]);const ttl=Math.min(Math.max(config.adminSessionMinutes,1)*60_000,ADMIN_TTL_MAX_MS);await client.query("INSERT INTO admin.sessions(id,user_id,parent_session_id,token_hash,expires_at) VALUES($1,$2,$3,$4,$5)",[crypto.randomUUID(),userId,parentSessionId,hashOpaqueToken(token),new Date(Date.now()+ttl)]);});return token;}
  async authenticateAdmin(token:string){const result=await this.pool.query<{user_id:string;admin_session_id:string;parent_session_id:string}>("SELECT * FROM admin.lookup_session($1)",[hashOpaqueToken(token)]);return result.rows[0]??null;}
  async reauthenticate(adminToken:string,userId:string,password:string,code:string){await this.verifyPassword(userId,password);await this.withUser(userId,async client=>{const row=(await client.query<SecretRow>("SELECT secret_ciphertext,secret_nonce,secret_tag,key_version,last_used_step FROM admin.mfa_methods WHERE user_id=$1 FOR UPDATE",[userId])).rows[0];if(!row)throw new Error("MFA_REQUIRED");const step=verifyTotp(decryptMfaSecret(row),code);if(step===null||BigInt(row.last_used_step??-1)>=BigInt(step))throw new Error("INVALID_MFA_CODE");await client.query("UPDATE admin.mfa_methods SET last_used_step=$2,updated_at=now() WHERE user_id=$1",[userId,step]);});const marked=await this.pool.query<{ok:boolean}>("SELECT admin.mark_reauthenticated($1) ok",[hashOpaqueToken(adminToken)]);if(!marked.rows[0]?.ok)throw new Error("ADMIN_SESSION_REQUIRED");}
  async overview(token:string){return(await this.pool.query<{overview:Record<string,unknown>}>("SELECT admin.overview($1) overview",[hashOpaqueToken(token)])).rows[0].overview;}
  async users(token:string){return(await this.pool.query("SELECT * FROM admin.users_page($1,50)",[hashOpaqueToken(token)])).rows;}
  async families(token:string){return(await this.pool.query("SELECT * FROM admin.families_page($1,50)",[hashOpaqueToken(token)])).rows;}
  async aiCatalog(token:string){const catalog=(await this.pool.query<{catalog:{providers:Array<{key:string;secretConfigured:boolean}>;models:unknown[]}}>("SELECT admin.ai_catalog($1) catalog",[hashOpaqueToken(token)])).rows[0].catalog;catalog.providers=catalog.providers.map(provider=>({...provider,secretConfigured:provider.key==="openrouter"&&Boolean(config.openrouterKey)}));return catalog;}
  async usageReport(token:string){return(await this.pool.query<{report:{byModel:unknown[];byFamily:unknown[];byUser:unknown[]}}>("SELECT admin.usage_report($1) report",[hashOpaqueToken(token)])).rows[0].report;}
  async systemStatus(token:string){const database=(await this.pool.query<{status:Record<string,unknown>}>("SELECT admin.system_status($1) status",[hashOpaqueToken(token)])).rows[0].status;return{...database,runtime:{nodeVersion:process.version,appUrl:config.appUrl,dataDirectory:config.dataDir,liveAIEnabled:config.liveAI,openRouterKeyConfigured:Boolean(config.openrouterKey),proxyConfigured:Boolean(config.proxyUrl),smtpConfigured:Boolean(config.smtpHost&&config.emailFrom),adminSessionMinutes:Math.min(Math.max(config.adminSessionMinutes,1),15)}};}
  async events(token:string){return(await this.pool.query<{events:{admin:Array<{action:string;[key:string]:unknown}>;security:unknown[];system:unknown[]}}>("SELECT admin.events_page($1,100) events",[hashOpaqueToken(token)])).rows[0].events;}
  async flags(token:string){return(await this.pool.query("SELECT flag_key,enabled,description,version,updated_at FROM admin.flags($1)",[hashOpaqueToken(token)])).rows;}
  async blockUser(token:string,target:string,blocked:boolean,reason:string,requestId:string){await this.pool.query("SELECT admin.block_user($1,$2,$3,$4,$5)",[hashOpaqueToken(token),target,blocked,reason,requestId]);}
  async revokeSessions(token:string,target:string,reason:string,requestId:string){await this.pool.query("SELECT admin.revoke_user_sessions($1,$2,$3,$4)",[hashOpaqueToken(token),target,reason,requestId]);}
  async setModelEnabled(token:string,target:string,enabled:boolean,reason:string,requestId:string){await this.pool.query("SELECT admin.set_model_enabled($1,$2,$3,$4,$5)",[hashOpaqueToken(token),target,enabled,reason,requestId]);}
  async setProviderEnabled(token:string,target:string,enabled:boolean,reason:string,requestId:string){await this.pool.query("SELECT admin.set_provider_enabled($1,$2,$3,$4,$5)",[hashOpaqueToken(token),target,enabled,reason,requestId]);}
  async setModelPrice(token:string,target:string,input:{promptMicrosPerMillion:number;completionMicrosPerMillion:number;currency:string;reason:string},requestId:string){return(await this.pool.query<{price_id:string}>("SELECT admin.set_model_price($1,$2,$3,$4,$5,$6,$7) price_id",[hashOpaqueToken(token),target,input.promptMicrosPerMillion,input.completionMicrosPerMillion,input.currency,input.reason,requestId])).rows[0];}
  async setFlag(token:string,input:{key:string;enabled:boolean;description:string;version:number;reason:string},requestId:string){return(await this.pool.query("SELECT flag_key,enabled,description,version,updated_at FROM admin.set_feature_flag($1,$2,$3,$4,$5,$6,$7)",[hashOpaqueToken(token),input.key,input.enabled,input.description,input.version,input.reason,requestId])).rows[0];}
  async record(token:string,action:string,result:string,requestId:string){await this.pool.query("SELECT admin.record_access($1,$2,$3,$4)",[hashOpaqueToken(token),action,result,requestId]);}
  private async verifyPassword(userId:string,password:string){const credential=await this.pool.query<{password_hash:string}>("SELECT * FROM identity.lookup_password_for_reauth($1)",[userId]);if(!credential.rows[0]||!await argon2.verify(credential.rows[0].password_hash,password).catch(()=>false))throw new Error("REAUTH_FAILED");}
  private async withUser<T>(userId:string,fn:(client:pg.PoolClient)=>Promise<T>){const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id','',true)",[userId]);const result=await fn(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}
