import type {ContentLesson} from "../../../types.js";
const lesson=(id:string,number:number,title:string,goal:string,items:Array<[string,string,string]>,explanation:string):ContentLesson=>({id,number,title,goal,minutes:20,explanation,practices:["Контекст","Сопоставление","Восстановление порядка","Интервальное повторение","Диалог"],words:items.map(([target,source,example])=>({target,source,example,hint:"Запоминайте глагол вместе с частицей и контекстом"}))});
export const phrasalVerbLessons:ContentLesson[]=[
 lesson("daily-routine",1,"Повседневные действия","Использовать базовые phrasal verbs в распорядке дня",[["wake up","просыпаться","I wake up at seven."],["get up","вставать с постели","I get up ten minutes later."],["put on","надевать","Put on your coat."],["take off","снимать одежду","Please take off your shoes."],["go out","выходить; проводить время вне дома","We go out on Fridays."],["come back","возвращаться","Come back before ten."]],"Phrasal verb состоит из глагола и частицы. Значение часто нельзя точно вывести из отдельных слов."),
 lesson("communication",2,"Общение","Понимать phrasal verbs в разговоре и переписке",[["call back","перезвонить","I'll call you back after lunch."],["speak up","говорить громче","Could you speak up, please?"],["find out","выяснить","Let's find out what happened."],["point out","указать, обратить внимание","She pointed out a mistake."],["bring up","поднять тему","He brought up an important question."],["get through","дозвониться; справиться","I couldn't get through to the office."]],"Некоторые глаголы разделяемые: call me back. Местоимение ставится между глаголом и частицей."),
 lesson("work-study",3,"Работа и учёба","Применять phrasal verbs в задачах и обучении",[["look up","искать информацию","Look up the word in a dictionary."],["write down","записывать","Write down the new phrase."],["hand in","сдавать работу","Please hand in your homework."],["catch up","догнать","I need to catch up with the class."],["work out","найти решение","We can work out a solution."],["go over","повторить, проверить","Let's go over the report."]],"Объект у разделяемого phrasal verb может стоять внутри: write the answer down."),
 lesson("travel-movement",4,"Движение и поездки","Понимать объявления и инструкции в поездке",[["set off","отправляться","We set off early in the morning."],["check in","регистрироваться","You can check in online."],["get on","садиться в транспорт","Get on the bus here."],["get off","выходить из транспорта","Get off at the next stop."],["pick up","забирать","I'll pick you up at the station."],["drop off","высадить; доставить","Can you drop me off near the hotel?"]],"Частица меняет значение: get on — войти в транспорт, get off — выйти."),
 lesson("problems-progress",5,"Проблемы и результат","Обсудить трудности и завершение задачи",[["give up","сдаваться, бросать","Don't give up."],["deal with","разбираться с","We need to deal with this problem."],["run out of","исчерпать запас","We've run out of time."],["figure out","разобраться, понять","I can't figure out the answer."],["carry on","продолжать","Carry on with the exercise."],["sort out","уладить, разобраться","We'll sort out the issue tomorrow."]],"Для устойчивого запоминания сравнивайте близкие выражения в полном предложении, а не в изолированном списке."),
];
