import type { ContentLesson } from "../types.js";

// Adapted from the three user-supplied ESL Vault worksheets (25 questions each).
// Stable page/item order retains provenance. Examples and child-friendly prompts are new.
type Item = [expression: string, meaning: string, example: string, question: string];
const pages: Item[][] = [
  [
    ["get along with", "ладить с", "I get along with my cousin.", "Who do you get along with at school?"],
    ["look at", "смотреть на", "I look at pictures of animals.", "What do you like to look at in a museum?"],
    ["wrap up", "заворачивать подарок", "I wrap up a present in blue paper.", "How would you wrap up a present for a friend?"],
    ["burn out", "переутомляться", "People can burn out if they never rest.", "How can taking breaks help people avoid burning out?"],
    ["dress up", "наряжаться", "I dress up for a birthday party.", "When do you like to dress up?"],
    ["count on", "рассчитывать на", "I can count on my friend.", "Who can you count on when you need help?"],
    ["stay up", "не ложиться спать", "I sometimes stay up to read.", "Do you stay up later at weekends?"],
    ["settle down", "остепениться; обосноваться", "My uncle wants to settle down in a small town.", "Where would a story character like to settle down?"],
    ["watch out for", "остерегаться", "Watch out for bikes on this path.", "What should explorers watch out for in a forest?"],
    ["get together", "собираться вместе", "We get together on Sundays.", "When do you get together with friends?"],
    ["plan on", "планировать сделать", "I plan on reading a comic.", "What do you plan on doing this weekend?"],
    ["help out", "помогать", "I help out by setting the table.", "How do you help out at home?"],
    ["think about", "думать о", "I think about tomorrow's game.", "What do you think about before a school trip?"],
    ["wash up", "мыть посуду", "We wash up after dinner.", "Who helps wash up in your family?"],
    ["calm down", "успокаиваться", "I take a slow breath to calm down.", "What helps you calm down before a test?"],
    ["hang out", "проводить время вместе", "I hang out with friends in the park.", "Where do you like to hang out with friends?"],
    ["go away", "уезжать", "We go away for a short holiday.", "Where would you like to go away for a weekend?"],
    ["sneak into", "пробираться незаметно в", "The cat sneaks into the kitchen.", "Why might a cat sneak into a kitchen in a story?"],
    ["try on", "примерять", "I try on a new jacket.", "What do you usually try on before buying it?"],
    ["run out of", "исчерпать запас", "We run out of milk on Sunday.", "What can you do if you run out of paper for a project?"],
    ["look up to", "уважать; брать пример с", "I look up to my coach.", "Who do you look up to, and why?"],
    ["get ahead", "добиваться успеха", "Regular practice helps me get ahead.", "What helps you get ahead in a hobby?"],
    ["take up", "начать заниматься", "I want to take up drawing.", "What new hobby would you like to take up?"],
    ["throw out", "выбрасывать", "We throw out broken pens.", "What can you reuse instead of throwing it out?"],
    ["show up", "появляться; приходить", "My friend shows up on time.", "Why is it helpful to show up on time for a team game?"],
  ],
  [
    ["flake out", "вырубаться от усталости", "I sometimes flake out on the sofa after a busy day.", "Does a story character ever flake out after an adventure?"],
    ["wind down", "расслабляться после дел", "I wind down by listening to music.", "How do you wind down after school?"],
    ["flag down", "останавливать взмахом руки", "An adult flags down a taxi.", "How can an adult flag down a taxi?"],
    ["take after", "быть похожим на родственника", "I take after my dad: we both love drawing.", "Who does a character in your favourite story take after?"],
    ["sit on", "сидеть на", "I sit on a soft cushion.", "What do you like to sit on when you read?"],
    ["let down", "подводить; разочаровывать", "I don't want to let my team down.", "How can friends avoid letting each other down?"],
    ["start out", "начинать путь или занятие", "We start out with a short story.", "How would you start out learning a new game?"],
    ["put on", "надевать", "I put on my cap before going outside.", "What would you put on for a sunny picnic?"],
    ["get around", "передвигаться", "We get around our town by bus.", "How do you get around with your family?"],
    ["fatten up", "откармливать", "The farmer fattens up the animals.", "In a farm story, why might a farmer fatten up an animal?"],
    ["break down", "ломаться", "The bus can break down.", "What could passengers do if their bus breaks down?"],
    ["put up with", "терпеть", "I put up with a little noise on the bus.", "What small inconvenience can you put up with on a trip?"],
    ["empty out", "полностью опустошать", "I empty out my school bag on Friday.", "When do you empty out your school bag?"],
    ["cheer up", "развеселить; приободрить", "A funny story can cheer me up.", "How can you cheer up a friend?"],
    ["move out", "съезжать", "The story's hero moves out of an old house.", "What should a story character pack before moving out?"],
    ["find out", "выяснять", "I use a dictionary to find out what a word means.", "How can you find out more about an animal?"],
    ["ask for", "просить", "I ask for some water.", "What would you ask for at a cafe?"],
    ["live with", "жить с", "The puppy lives with a kind family.", "Who does your favourite story character live with?"],
    ["give up", "бросать; сдаваться", "I don't give up when a puzzle is hard.", "What helps you not to give up?"],
    ["set off", "отправляться в путь", "We set off after breakfast.", "What would you pack before setting off on a school trip?"],
    ["branch out", "пробовать новое направление", "Our club wants to branch out into painting.", "How could your school club branch out?"],
    ["shave off", "сбривать", "The actor shaves off his beard for a new role.", "Why might an actor shave off a beard for a role?"],
    ["run over", "переезжать; наезжать на", "A car could run over a toy left in the road.", "Why should we never leave toys where cars could run over them?"],
    ["die off", "постепенно вымирать", "Some plants die off when there is no rain.", "Why might plants die off during a very dry summer?"],
    ["finish off", "доедать; заканчивать", "I finish off the last piece of my sandwich.", "What small task would you like to finish off today?"],
  ],
  [
    ["turn off", "выключать", "I turn off the light before bed.", "What do you turn off before going to sleep?"],
    ["bring up", "воспитывать", "My grandparents brought up three children.", "What can adults teach children as they bring them up?"],
    ["sleep through", "проспать, не проснувшись от", "My cat can sleep through a noisy film.", "Can a pet sleep through a noisy film?"],
    ["fry up", "быстро пожарить еду", "An adult fries up some eggs.", "What could an adult fry up for breakfast?"],
    ["freeze over", "покрываться льдом", "The pond freezes over in winter.", "What happens to a pond when it freezes over?"],
    ["get around to", "наконец найти время на", "I finally get around to sorting my books.", "What small project would you like to get around to doing?"],
    ["pick out", "выбирать", "I pick out a book from the shelf.", "How do you pick out a book to read?"],
    ["walk through", "проходить через", "We walk through a forest with a guide.", "What might you see while walking through a forest?"],
    ["tie up", "завязывать", "I tie up my shoelaces before running.", "When do you need to tie up your shoelaces?"],
    ["throw up", "испытывать рвоту", "A sick character feels as if he might throw up.", "Who should a child tell if they feel they might throw up?"],
    ["move across", "двигаться через", "The ship moves across the ocean.", "What can move across an ocean?"],
    ["break into", "вламываться в", "In the story, a thief tries to break into a museum.", "Who stops the thief trying to break into a museum in a story?"],
    ["mess around", "баловаться; отвлекаться", "We don't mess around during a lesson.", "Why is it better not to mess around when someone is speaking?"],
    ["save up", "копить деньги", "I save up for a board game.", "What would you like to save up for?"],
    ["warm up", "разогревать", "An adult warms up the soup.", "What food could an adult warm up for lunch?"],
    ["chill out", "расслабляться", "I chill out with a comic.", "How do you like to chill out at weekends?"],
    ["ride on", "ехать верхом на; кататься на", "The toy character rides on a wooden horse.", "Would a toy character like to ride on a wooden horse?"],
    ["look up", "разыскать человека", "My aunt looks up an old friend when she visits the town.", "Why might an adult look up an old friend?"],
    ["hand down", "передавать младшим", "We hand down books to younger cousins.", "What could a family hand down to younger children?"],
    ["go without", "обходиться без", "I can go without a new toy this week.", "What optional thing could you go without to save money?"],
    ["agree with", "соглашаться с", "I agree with my friend about this game.", "Do you always agree with friends about the best game?"],
    ["freak out", "сильно пугаться; паниковать", "The character freaks out when the lights go out.", "How could a friend help a character who is starting to freak out?"],
    ["start up", "основывать; запускать", "We want to start up a school club.", "What school club would you like to start up?"],
    ["cook up", "приготовить; придумать", "We cook up a plan for a surprise party.", "What fun plan could you cook up with your friends?"],
    ["wake up", "просыпаться", "I wake up at seven on school days.", "What time do you wake up at weekends?"],
  ],
];
const titles = ["Знакомства и праздники", "Поддержка и встречи", "Дом и спокойствие", "Прогулки и покупки", "Увлечения и пример для подражания", "Отдых и семья", "Начинаем новое", "Трудности и поддержка", "Находим ответы и отправляемся в путь", "Новые идеи и завершение дел", "Дом, завтрак и зима", "Выбираем и действуем", "Истории и полезные привычки", "Отдых и бережливость", "Мнения и планы"];
export const photoConversationLessons: ContentLesson[] = pages.flatMap((page, pageIndex) => Array.from({ length: 5 }, (_, group) => {
  const items = page.slice(group * 5, group * 5 + 5), position = pageIndex * 5 + group;
  return {
    id: `photo-${pageIndex + 1}-${group + 1}`, number: position + 6, title: titles[position], minutes: 15,
    goal: "Ответить на пять разговорных вопросов с устойчивыми выражениями",
    explanation: "Сначала разберите выражение в примере, затем ответьте о себе или о вымышленном герое. Добавьте because и причину. Сочетания с предлогом (look at, agree with, sit on) здесь тоже есть, но не каждое сочетание — идиоматический phrasal verb. Значение зависит от контекста: bring up — воспитывать или поднимать тему; look up — искать слово или разыскать человека. Слова flake out, chill out и freak out разговорные. Обсуждать личный опыт не обязательно.",
    practices: ["Карточки", "Аудирование", "Произношение", "Проверка", "Разговорная практика"],
    words: items.map(([target, source, example]) => ({ target, source, example, hint: "Прочитайте полный пример: он подскажет нужное значение и место дополнения." })),
    conversation: items.map(([, , modelAnswer, question]) => ({ question, modelAnswer, tip: "Дайте свой ответ из 1–2 предложений. Можно придумать героя. Образец показывает форму, но не является единственным правильным ответом." })),
  };
}));
