CREATE SCHEMA learning AUTHORIZATION langtutor_owner;
CREATE TABLE learning.languages(id uuid PRIMARY KEY,key text NOT NULL UNIQUE,name text NOT NULL);
CREATE TABLE learning.programs(id uuid PRIMARY KEY,language_id uuid NOT NULL REFERENCES learning.languages(id),key text NOT NULL UNIQUE,name text NOT NULL,source_locale text NOT NULL);
CREATE TABLE learning.courses(id uuid PRIMARY KEY,program_id uuid NOT NULL REFERENCES learning.programs(id),key text NOT NULL UNIQUE,name text NOT NULL);
CREATE TABLE learning.course_versions(id uuid PRIMARY KEY,course_id uuid NOT NULL REFERENCES learning.courses(id),version integer NOT NULL,status text NOT NULL CHECK(status IN('draft','published','retired')),published_at timestamptz,UNIQUE(course_id,version));
CREATE TABLE learning.lessons(id uuid PRIMARY KEY,course_version_id uuid NOT NULL REFERENCES learning.course_versions(id),lesson_key text NOT NULL,title text NOT NULL,position integer NOT NULL,content jsonb NOT NULL,UNIQUE(course_version_id,lesson_key));
CREATE TABLE learning.exercises(id uuid PRIMARY KEY,lesson_id uuid NOT NULL REFERENCES learning.lessons(id),exercise_key text NOT NULL,type text NOT NULL,position integer NOT NULL,content jsonb NOT NULL,UNIQUE(lesson_id,exercise_key));
CREATE TABLE learning.course_enrollments(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,course_id uuid NOT NULL REFERENCES learning.courses(id),course_version_id uuid NOT NULL REFERENCES learning.course_versions(id),status text NOT NULL DEFAULT 'active',enrolled_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,course_id));
CREATE TABLE learning.lesson_progress(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,course_id uuid NOT NULL,course_version_id uuid NOT NULL,lesson_key text NOT NULL,current_step integer NOT NULL DEFAULT 0,completion_percent integer NOT NULL DEFAULT 0 CHECK(completion_percent BETWEEN 0 AND 100),completed boolean NOT NULL DEFAULT false,score numeric(5,2),version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,course_id,lesson_key));
CREATE TABLE learning.exercise_attempts(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,course_id uuid NOT NULL,course_version_id uuid NOT NULL,lesson_key text NOT NULL,exercise_key text NOT NULL,skill_type text NOT NULL,score numeric(5,2) NOT NULL,feedback text,source text NOT NULL DEFAULT 'deterministic',model_id uuid,rubric_version text,confidence numeric(5,4),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE learning.skill_scores(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,course_id uuid NOT NULL,skill_key text NOT NULL,mastery numeric(5,2) NOT NULL,scoring_version integer NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,course_id,skill_key));
CREATE TABLE learning.vocabulary_items(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,course_id uuid NOT NULL,term text NOT NULL,translation text NOT NULL,example_target text,example_source text,lesson_key text,status text NOT NULL DEFAULT 'new',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,course_id,term));
CREATE TABLE learning.review_schedule(vocabulary_id uuid PRIMARY KEY REFERENCES learning.vocabulary_items(id) ON DELETE CASCADE,user_id uuid NOT NULL,interval_days integer NOT NULL DEFAULT 1,repetitions integer NOT NULL DEFAULT 0,correct_count integer NOT NULL DEFAULT 0,error_count integer NOT NULL DEFAULT 0,next_review_at timestamptz NOT NULL);
CREATE TABLE learning.user_learning_settings(user_id uuid PRIMARY KEY REFERENCES identity.users(id) ON DELETE CASCADE,values jsonb NOT NULL DEFAULT '{}'::jsonb,version integer NOT NULL DEFAULT 1,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE learning.events(id uuid PRIMARY KEY,user_id uuid NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE learning.legacy_profile_links(user_id uuid PRIMARY KEY REFERENCES identity.users(id) ON DELETE CASCADE,legacy_anonymous_id uuid NOT NULL UNIQUE,linked_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE learning.legacy_imports(id uuid PRIMARY KEY,user_id uuid NOT NULL,source_fingerprint text NOT NULL,status text NOT NULL,counts jsonb NOT NULL,imported_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,source_fingerprint));

DO $$ DECLARE table_name text; BEGIN FOREACH table_name IN ARRAY ARRAY['course_enrollments','lesson_progress','exercise_attempts','skill_scores','vocabulary_items','review_schedule','user_learning_settings','events','legacy_profile_links','legacy_imports'] LOOP EXECUTE format('ALTER TABLE learning.%I ENABLE ROW LEVEL SECURITY',table_name); EXECUTE format('ALTER TABLE learning.%I FORCE ROW LEVEL SECURITY',table_name); EXECUTE format('CREATE POLICY user_scope ON learning.%I USING (user_id=nullif(current_setting(''app.user_id'',true),'''')::uuid) WITH CHECK (user_id=nullif(current_setting(''app.user_id'',true),'''')::uuid)',table_name); END LOOP; END $$;

ALTER TABLE learning.languages OWNER TO langtutor_owner; ALTER TABLE learning.programs OWNER TO langtutor_owner; ALTER TABLE learning.courses OWNER TO langtutor_owner; ALTER TABLE learning.course_versions OWNER TO langtutor_owner; ALTER TABLE learning.lessons OWNER TO langtutor_owner; ALTER TABLE learning.exercises OWNER TO langtutor_owner;
ALTER TABLE learning.course_enrollments OWNER TO langtutor_owner; ALTER TABLE learning.lesson_progress OWNER TO langtutor_owner; ALTER TABLE learning.exercise_attempts OWNER TO langtutor_owner; ALTER TABLE learning.skill_scores OWNER TO langtutor_owner; ALTER TABLE learning.vocabulary_items OWNER TO langtutor_owner; ALTER TABLE learning.review_schedule OWNER TO langtutor_owner; ALTER TABLE learning.user_learning_settings OWNER TO langtutor_owner; ALTER TABLE learning.events OWNER TO langtutor_owner; ALTER TABLE learning.legacy_profile_links OWNER TO langtutor_owner; ALTER TABLE learning.legacy_imports OWNER TO langtutor_owner;
GRANT USAGE ON SCHEMA learning TO langtutor_runtime;
GRANT SELECT ON learning.languages,learning.programs,learning.courses,learning.course_versions,learning.lessons,learning.exercises TO langtutor_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON learning.course_enrollments,learning.lesson_progress,learning.exercise_attempts,learning.skill_scores,learning.vocabulary_items,learning.review_schedule,learning.user_learning_settings,learning.events,learning.legacy_profile_links,learning.legacy_imports TO langtutor_runtime;
