CREATE OR REPLACE FUNCTION admin.usage_report(p_token_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,admin,ai,identity,families AS $$
DECLARE v_actor uuid;v_result jsonb;BEGIN v_actor:=admin.require_session(p_token_hash,false);
 SELECT jsonb_build_object(
  'byModel',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM(SELECT m.model_key "modelKey",sum(l.prompt_tokens+l.completion_tokens) tokens,sum(l.cost_micros) "costMicros",count(*) requests FROM ai.usage_ledger l JOIN ai.models m ON m.id=l.model_id WHERE l.created_at>=date_trunc('month',now()) GROUP BY m.model_key ORDER BY tokens DESC)x),'[]'::jsonb),
  'byFamily',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM(SELECT l.family_id "familyId",coalesce(f.name,'Без семьи') name,sum(l.prompt_tokens+l.completion_tokens) tokens,sum(l.cost_micros) "costMicros" FROM ai.usage_ledger l LEFT JOIN families.families f ON f.id=l.family_id WHERE l.created_at>=date_trunc('month',now()) GROUP BY l.family_id,f.name ORDER BY tokens DESC LIMIT 100)x),'[]'::jsonb),
  'byUser',coalesce((SELECT jsonb_agg(to_jsonb(x)) FROM(SELECT l.user_id "userId",u.display_name "displayName",sum(l.prompt_tokens+l.completion_tokens) tokens,sum(l.cost_micros) "costMicros" FROM ai.usage_ledger l JOIN identity.users u ON u.id=l.user_id WHERE l.created_at>=date_trunc('month',now()) GROUP BY l.user_id,u.display_name ORDER BY tokens DESC LIMIT 100)x),'[]'::jsonb)
 ) INTO v_result;RETURN v_result;END$$;
REVOKE ALL ON FUNCTION admin.usage_report(text) FROM PUBLIC;ALTER FUNCTION admin.usage_report(text) OWNER TO langtutor_authenticator;GRANT EXECUTE ON FUNCTION admin.usage_report(text) TO langtutor_runtime;

CREATE OR REPLACE FUNCTION admin.set_provider_enabled(p_token_hash text,p_provider uuid,p_enabled boolean,p_reason text,p_request_id uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,admin,ai AS $$DECLARE v_actor uuid;BEGIN v_actor:=admin.require_session(p_token_hash,true);IF char_length(trim(p_reason))<5 THEN RAISE EXCEPTION 'ADMIN_REASON_REQUIRED' USING ERRCODE='P0001';END IF;UPDATE ai.providers SET enabled=p_enabled WHERE id=p_provider;IF NOT FOUND THEN RAISE EXCEPTION 'PROVIDER_NOT_FOUND' USING ERRCODE='P0001';END IF;INSERT INTO admin.access_events(id,admin_user_id,action,target_type,target_id,reason,result,request_id)VALUES(gen_random_uuid(),v_actor,'admin.ai_provider.enabled_changed','ai_provider',p_provider::text,left(p_reason,500),'success',p_request_id);END$$;
REVOKE ALL ON FUNCTION admin.set_provider_enabled(text,uuid,boolean,text,uuid) FROM PUBLIC;ALTER FUNCTION admin.set_provider_enabled(text,uuid,boolean,text,uuid) OWNER TO langtutor_authenticator;GRANT EXECUTE ON FUNCTION admin.set_provider_enabled(text,uuid,boolean,text,uuid) TO langtutor_runtime;

CREATE OR REPLACE FUNCTION admin.set_model_price(p_token_hash text,p_model uuid,p_prompt bigint,p_completion bigint,p_currency char(3),p_reason text,p_request_id uuid) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,admin,ai AS $$DECLARE v_actor uuid;v_id uuid:=gen_random_uuid();BEGIN v_actor:=admin.require_session(p_token_hash,true);IF char_length(trim(p_reason))<5 THEN RAISE EXCEPTION 'ADMIN_REASON_REQUIRED' USING ERRCODE='P0001';END IF;IF p_prompt<0 OR p_completion<0 OR upper(p_currency)!~'^[A-Z]{3}$' THEN RAISE EXCEPTION 'INVALID_PRICE' USING ERRCODE='P0001';END IF;IF NOT EXISTS(SELECT 1 FROM ai.models WHERE id=p_model)THEN RAISE EXCEPTION 'MODEL_NOT_FOUND' USING ERRCODE='P0001';END IF;UPDATE ai.price_versions SET effective_to=now() WHERE model_id=p_model AND effective_to IS NULL;INSERT INTO ai.price_versions(id,model_id,effective_from,prompt_micros_per_million,completion_micros_per_million,currency)VALUES(v_id,p_model,now(),p_prompt,p_completion,upper(p_currency));INSERT INTO admin.access_events(id,admin_user_id,action,target_type,target_id,reason,result,request_id)VALUES(gen_random_uuid(),v_actor,'admin.ai_price.version_created','ai_model',p_model::text,left(p_reason,500),'success',p_request_id);RETURN v_id;END$$;
REVOKE ALL ON FUNCTION admin.set_model_price(text,uuid,bigint,bigint,char,text,uuid) FROM PUBLIC;ALTER FUNCTION admin.set_model_price(text,uuid,bigint,bigint,char,text,uuid) OWNER TO langtutor_authenticator;GRANT EXECUTE ON FUNCTION admin.set_model_price(text,uuid,bigint,bigint,char,text,uuid) TO langtutor_runtime;
