CREATE TABLE admin.user_blocks(user_id uuid PRIMARY KEY REFERENCES identity.users(id) ON DELETE CASCADE,previous_status identity.user_status NOT NULL,reason text NOT NULL,blocked_by uuid NOT NULL REFERENCES identity.users(id),blocked_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE admin.user_blocks ENABLE ROW LEVEL SECURITY;ALTER TABLE admin.user_blocks FORCE ROW LEVEL SECURITY;
ALTER TABLE admin.user_blocks OWNER TO langtutor_owner;GRANT SELECT,INSERT,DELETE ON admin.user_blocks TO langtutor_authenticator;

CREATE FUNCTION admin.prevent_mfa_reenrollment() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,admin AS $$BEGIN IF EXISTS(SELECT 1 FROM admin.mfa_methods WHERE user_id=NEW.user_id)THEN RAISE EXCEPTION 'MFA_ALREADY_ENABLED' USING ERRCODE='P0001';END IF;RETURN NEW;END$$;
ALTER FUNCTION admin.prevent_mfa_reenrollment() OWNER TO langtutor_owner;
CREATE TRIGGER prevent_mfa_reenrollment BEFORE INSERT OR UPDATE ON admin.mfa_enrollments FOR EACH ROW EXECUTE FUNCTION admin.prevent_mfa_reenrollment();

CREATE OR REPLACE FUNCTION admin.block_user(p_token_hash text,p_target uuid,p_block boolean,p_reason text,p_request_id uuid) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,admin,identity,operations AS $$DECLARE v_actor uuid;v_status identity.user_status;BEGIN v_actor:=admin.require_session(p_token_hash,true);IF v_actor=p_target THEN RAISE EXCEPTION 'ADMIN_SELF_MUTATION_FORBIDDEN' USING ERRCODE='P0001';END IF;IF char_length(trim(p_reason))<5 THEN RAISE EXCEPTION 'ADMIN_REASON_REQUIRED' USING ERRCODE='P0001';END IF;SELECT status INTO v_status FROM identity.users WHERE id=p_target AND NOT is_super_admin FOR UPDATE;IF v_status IS NULL THEN RAISE EXCEPTION 'USER_NOT_FOUND_OR_PROTECTED' USING ERRCODE='P0001';END IF;
 IF p_block THEN INSERT INTO admin.user_blocks(user_id,previous_status,reason,blocked_by)VALUES(p_target,v_status,left(p_reason,500),v_actor)ON CONFLICT(user_id)DO NOTHING;UPDATE identity.users SET status='blocked',updated_at=now() WHERE id=p_target;UPDATE identity.sessions SET revoked_at=now() WHERE user_id=p_target AND revoked_at IS NULL;UPDATE identity.refresh_tokens SET revoked_at=now() WHERE user_id=p_target AND revoked_at IS NULL;
 ELSE UPDATE identity.users u SET status=b.previous_status,updated_at=now() FROM admin.user_blocks b WHERE b.user_id=p_target AND u.id=b.user_id;IF NOT FOUND THEN RAISE EXCEPTION 'USER_BLOCK_RECORD_NOT_FOUND' USING ERRCODE='P0001';END IF;DELETE FROM admin.user_blocks WHERE user_id=p_target;END IF;
 INSERT INTO admin.access_events(id,admin_user_id,action,target_type,target_id,reason,result,request_id)VALUES(gen_random_uuid(),v_actor,CASE WHEN p_block THEN 'admin.user.blocked' ELSE 'admin.user.unblocked' END,'user',p_target::text,left(p_reason,500),'success',p_request_id);INSERT INTO operations.security_events(id,severity,actor_user_id,code,safe_details,request_id)VALUES(gen_random_uuid(),'warning',v_actor,CASE WHEN p_block THEN 'USER_BLOCKED' ELSE 'USER_UNBLOCKED' END,jsonb_build_object('targetUserId',p_target),p_request_id);END$$;
REVOKE ALL ON FUNCTION admin.block_user(text,uuid,boolean,text,uuid) FROM PUBLIC;ALTER FUNCTION admin.block_user(text,uuid,boolean,text,uuid) OWNER TO langtutor_authenticator;GRANT EXECUTE ON FUNCTION admin.block_user(text,uuid,boolean,text,uuid) TO langtutor_runtime;
