export type Lesson={id:string;number:number;title:string;goal:string;minutes:number;words:{it:string;ru:string;example:string;hint:string}[];explanation:string;practices:string[]};
export const lessons:Lesson[]=[
{id:'greetings',number:1,title:'Приветствие и знакомство',goal:'Поздороваться, представиться и спросить имя',minutes:15,explanation:'Ciao — неформальное приветствие и прощание. Buongiorno — нейтральнее и вежливее. Mi chiamo… помогает назвать имя, Come ti chiami? — спросить его в неформальном общении, а Piacere! говорят при знакомстве.',practices:['Слова','Чтение','Письмо','Аудирование','Произношение','Проверка'],words:[['Ciao','Привет / Пока','Ciao, Marco!','Чао'],['Buongiorno','Доброе утро / Добрый день','Buongiorno, signora!','буон-ДЖОР-но'],['Arrivederci','До свидания','Arrivederci!','ар-ри-ве-ДЕР-чи'],['Come ti chiami?','Как тебя зовут?','Come ti chiami?','КО-ме ти КЬЯ-ми'],['Mi chiamo…','Меня зовут…','Mi chiamo Anna.','ми КЬЯ-мо'],['Piacere!','Приятно познакомиться!','Piacere!','пья-ЧЕ-ре'],['Grazie','Спасибо','Grazie!','ГРА-цье'],['Prego','Пожалуйста','Prego.','ПРЕ-го']].map(([it,ru,example,hint])=>({it,ru,example,hint}))},
{id:'reading',number:2,title:'Алфавит и первые правила чтения',goal:'Узнавать ключевые сочетания букв',minutes:15,explanation:'C перед a, o, u звучит твёрдо; перед e, i — мягче. Ch сохраняет твёрдый звук. G, gh и gn запоминаем на живых примерах.',practices:['Чтение','Выбор варианта','Аудирование'],words:['casa','cena','chi','che','gelato','spaghetti','gnocchi','famiglia'].map(it=>({it,ru:{casa:'дом',cena:'ужин',chi:'кто',che:'что',gelato:'мороженое',spaghetti:'спагетти',gnocchi:'ньокки',famiglia:'семья'}[it]!,example:`La parola «${it}».`,hint:'Послушайте и повторите'}))},
{id:'numbers',number:3,title:'Числа от 0 до 20',goal:'Назвать возраст, телефон и количество',minutes:18,explanation:'Числа пригодятся для возраста, номера телефона, времени и покупок.',practices:['Карточки','Аудирование','Счёт'],words:['zero','uno','due','tre','quattro','cinque','sei','sette','otto','nove','dieci','undici','dodici','tredici','quattordici','quindici','sedici','diciassette','diciotto','diciannove','venti'].map((it,i)=>({it,ru:String(i),example:`Ho ${it} libri.`,hint:'Повторите число'}))},
{id:'cafe',number:4,title:'Заказ в кафе',goal:'Вежливо заказать и попросить счёт',minutes:18,explanation:'Vorrei… — мягкий и вежливый способ попросить желаемое. Добавьте per favore.',practices:['Диалог','Письмо','Аудирование'],words:[['Vorrei…','Я хотел(а) бы…'],['un caffè','кофе'],['un’acqua','воду'],['per favore','пожалуйста'],['il conto','счёт'],['Quanto costa?','Сколько стоит?'],['Grazie','Спасибо'],['Prego','Пожалуйста']].map(([it,ru])=>({it,ru,example:`${it}, per favore.`,hint:'Говорите спокойно'}))},
{id:'city',number:5,title:'Город и транспорт',goal:'Спросить дорогу и купить билет',minutes:20,explanation:'Dov’è…? означает «Где…?». Destra — направо, sinistra — налево.',practices:['Карта','Диалог','Аудирование'],words:[['Dov’è…?','Где…?'],['la stazione','станция'],['il biglietto','билет'],['l’autobus','автобус'],['a destra','направо'],['a sinistra','налево'],['vicino','близко'],['lontano','далеко']].map(([it,ru])=>({it,ru,example:`Dov’è ${it}?`,hint:'Повторите по частям'}))},
{id:'hotel',number:6,title:'Заселение в отель',goal:'Назвать бронь и получить ключ',minutes:20,explanation:'Ho una prenotazione — «У меня есть бронь». Числа из первого блока помогут понять номер комнаты и количество ночей.',practices:['Диалог','Аудирование','Произношение','Проверка'],words:[['Ho una prenotazione','У меня есть бронь'],['una camera','номер / комната'],['per una notte','на одну ночь'],['il documento','документ'],['la chiave','ключ'],['la camera numero…','номер комнаты…'],['Dov’è la camera?','Где находится номер?'],['Ecco, grazie','Вот, спасибо']].map(([it,ru])=>({it,ru,example:`${it}.`,hint:'Представьте разговор на стойке отеля'}))},
{id:'time',number:7,title:'Время и планы на день',goal:'Спросить время и договориться о встрече',minutes:20,explanation:'È l’una говорят про один час, Sono le… — про остальные часы. Alle… означает «в … часов».',practices:['Часы','Диалог','Аудирование','Проверка'],words:[['Che ore sono?','Который час?'],['È l’una','Сейчас час'],['Sono le due','Сейчас два часа'],['A che ora?','Во сколько?'],['alle tre','в три часа'],['oggi','сегодня'],['domani','завтра'],['la sera','вечером']].map(([it,ru])=>({it,ru,example:`Ci vediamo ${it}.`,hint:'Свяжите фразу со знакомыми числами'}))},
{id:'food',number:8,title:'Еда и предпочтения',goal:'Заказать еду и сказать о предпочтениях',minutes:20,explanation:'Mi piace… — «Мне нравится…», Non mi piace… — «Мне не нравится…». Senza помогает попросить блюдо без ингредиента.',practices:['Диалог','Письмо','Аудирование','Проверка'],words:[['Ho fame','Я голоден / голодна'],['Ho sete','Я хочу пить'],['Mi piace…','Мне нравится…'],['Non mi piace…','Мне не нравится…'],['Vorrei mangiare…','Я хотел(а) бы поесть…'],['la pizza','пицца'],['il formaggio','сыр'],['senza formaggio','без сыра']].map(([it,ru])=>({it,ru,example:`${it}.`,hint:'Скажите о своём настоящем предпочтении'}))},
{id:'shopping',number:9,title:'Покупки и цены',goal:'Выбрать товар, уточнить цену и оплату',minutes:20,explanation:'Questo и questa означают «это/этот/эта». Форма зависит от слова. Quanto costa? уже знакомо по кафе и теперь применяется в магазине.',practices:['Ролевая игра','Числа','Произношение','Проверка'],words:[['Vorrei questo','Я хотел(а) бы это'],['Quanto costa?','Сколько это стоит?'],['È troppo caro','Это слишком дорого'],['Va bene','Подходит / хорошо'],['piccolo','маленький'],['grande','большой'],['rosso','красный'],['Posso pagare con la carta?','Можно оплатить картой?']].map(([it,ru])=>({it,ru,example:`${it}.`,hint:'Представьте покупку в небольшом магазине'}))},
{id:'help',number:10,title:'Просьба о помощи',goal:'Объяснить простую проблему и понять инструкцию',minutes:22,explanation:'Mi scusi привлекает внимание вежливо. Если речь слишком быстрая, попросите повторить или говорить медленнее.',practices:['Ситуация','Диалог','Аудирование','Мини-экзамен'],words:[['Mi scusi','Извините'],['Ho bisogno di aiuto','Мне нужна помощь'],['Non capisco','Я не понимаю'],['Può ripetere, per favore?','Повторите, пожалуйста'],['Parli più lentamente, per favore','Говорите медленнее, пожалуйста'],['Ho perso il biglietto','Я потерял(а) билет'],['il telefono','телефон'],['la farmacia','аптека']].map(([it,ru])=>({it,ru,example:`${it}.`,hint:'Говорите коротко и спокойно'}))}];
export const scenarios=[
{id:'intro',title:'Знакомство',goal:'Представиться и продолжить беседу',phrases:'Mi chiamo…, Piacere!',minutes:5,lessonId:'greetings'},
{id:'cafe',title:'Заказ в кафе',goal:'Сделать заказ и попросить счёт',phrases:'Vorrei…, per favore',minutes:7,lessonId:'cafe'},
{id:'ticket',title:'Покупка билета',goal:'Купить билет и понять направление',phrases:'Un biglietto, per favore',minutes:7,lessonId:'city'},
{id:'hotel',title:'Заселение в отель',goal:'Назвать бронь и получить ключ',phrases:'Ho una prenotazione',minutes:8,lessonId:'hotel'},
{id:'time',title:'Договориться о времени',goal:'Уточнить время встречи',phrases:'A che ora? Alle tre.',minutes:7,lessonId:'time'},
{id:'food',title:'Выбрать еду',goal:'Сказать о предпочтениях',phrases:'Mi piace…, senza…',minutes:7,lessonId:'food'},
{id:'shopping',title:'Покупка в магазине',goal:'Выбрать товар и оплатить',phrases:'Vorrei questo. Quanto costa?',minutes:8,lessonId:'shopping'},
{id:'directions',title:'Как пройти',goal:'Спросить дорогу',phrases:'Dov’è…?',minutes:7,lessonId:'city'},
{id:'help',title:'Попросить о помощи',goal:'Объяснить проблему',phrases:'Ho bisogno di aiuto',minutes:8,lessonId:'help'}];
