import {useEffect,useState} from "react";
import type {FormEvent} from "react";

type Phase="loading"|"hidden"|"enroll"|"verify"|"dashboard";
type UserRow={user_id:string;email:string;display_name:string;status:string;is_super_admin:boolean;family_id:string|null;family_role:string|null;tokens_this_month:string;cost_micros_this_month:string};
type FamilyRow={family_id:string;name:string;member_count:string;tokens_this_month:string;cost_micros_this_month:string};
type ModelRow={id:string;key:string;name:string;enabled:boolean;upstreamModel:string};
type UsageRow={modelKey:string;tokens:string;costMicros:string;requests:string};
const api=async<T,>(path:string,init?:RequestInit):Promise<T>=>{const response=await fetch(`/api/v1/admin${path}`,{credentials:"include",headers:{"content-type":"application/json",...(init?.headers??{})},...init});const body=response.status===204?null:await response.json();if(!response.ok)throw Object.assign(new Error(body?.error?.message??"Ошибка запроса"),{status:response.status,code:body?.error?.code});return body as T;};

export function ControlPage(){const[phase,setPhase]=useState<Phase>("loading"),[message,setMessage]=useState("Проверяем защищённый доступ…"),[password,setPassword]=useState(""),[code,setCode]=useState(""),[setup,setSetup]=useState<{secret:string;otpauthUrl:string}|null>(null),[overview,setOverview]=useState<Record<string,number|string>>({}),[users,setUsers]=useState<UserRow[]>([]),[families,setFamilies]=useState<FamilyRow[]>([]),[models,setModels]=useState<ModelRow[]>([]),[events,setEvents]=useState<Array<{severity:string;code:string;created_at:string}>>([]),[reason,setReason]=useState(""),[reauthUntil,setReauthUntil]=useState(0);
  useEffect(()=>{api<{enabled:boolean}>("/mfa/status").then(status=>{setPhase(status.enabled?"verify":"enroll");setMessage(status.enabled?"Введите код из приложения-аутентификатора":"Настройте обязательную MFA")}).catch(error=>{setPhase("hidden");setMessage((error as {status?:number}).status===404?"Страница не найдена":"Защищённый контур недоступен")});},[]);
  const load=async()=>{const[o,u,f,a,r,e]=await Promise.all([api<Record<string,number|string>>("/overview"),api<{users:UserRow[]}>("/users"),api<{families:FamilyRow[]}>("/families"),api<{models:ModelRow[]}>("/ai"),api<{byModel:UsageRow[]}>("/usage"),api<{security:Array<{severity:string;code:string;created_at:string}>}>("/events")]);setOverview(o);setUsers(u.users);setFamilies(f.families);setModels(a.models);setEvents(e.security);setPhase("dashboard");setMessage(`Данные обновлены · моделей с usage: ${r.byModel.length}`)};
  const enroll=async(event:FormEvent)=>{event.preventDefault();try{setSetup(await api("/mfa/enroll",{method:"POST",body:JSON.stringify({password})}));setPassword("");setMessage("Добавьте ключ в приложение и подтвердите шестизначным кодом")}catch(error){setMessage((error as Error).message)}};
  const activate=async(event:FormEvent)=>{event.preventDefault();try{await api("/mfa/activate",{method:"POST",body:JSON.stringify({code})});setSetup(null);setPhase("verify");setMessage("MFA включена. Подтвердите вход кодом") }catch(error){setMessage((error as Error).message)}finally{setCode("")}};
  const verify=async(event:FormEvent)=>{event.preventDefault();try{await api("/session",{method:"POST",body:JSON.stringify({code})});await load()}catch(error){setMessage((error as Error).message)}finally{setCode("")}};
  const reauth=async(event:FormEvent)=>{event.preventDefault();try{await api("/reauth",{method:"POST",body:JSON.stringify({password,code})});setReauthUntil(Date.now()+120_000);setPassword("");setCode("");setMessage("Опасные действия подтверждены на 2 минуты")}catch(error){setMessage((error as Error).message)}};
  const block=async(user:UserRow)=>{if(Date.now()>reauthUntil){setMessage("Сначала выполните повторное подтверждение");return}try{await api(`/users/${user.user_id}/status`,{method:"PUT",body:JSON.stringify({blocked:user.status!=="blocked",reason})});setReason("");await load()}catch(error){setMessage((error as Error).message)}};
  const toggleModel=async(model:ModelRow)=>{if(Date.now()>reauthUntil){setMessage("Сначала выполните повторное подтверждение");return}try{await api(`/ai/models/${model.id}`,{method:"PUT",body:JSON.stringify({enabled:!model.enabled,reason})});setReason("");await load()}catch(error){setMessage((error as Error).message)}};
  if(phase==="loading"||phase==="hidden")return <main className="page narrow"><h1>{phase==="hidden"?"404":"Панель управления"}</h1><p role="status">{message}</p></main>;
  if(phase==="enroll")return <main className="page narrow"><h1>Защищённая настройка MFA</h1><p role="status">{message}</p>{!setup?<form onSubmit={enroll}><label>Текущий пароль<input type="password" autoComplete="current-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button type="submit">Создать ключ MFA</button></form>:<><p>Секрет показывается только сейчас:</p><code className="control-secret">{setup.secret}</code><details><summary>URI для ручного импорта</summary><code>{setup.otpauthUrl}</code></details><form onSubmit={activate}><label>Код из приложения<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)}/></label><button type="submit">Включить MFA</button></form></>}</main>;
  if(phase==="verify")return <main className="page narrow"><h1>Super Admin</h1><p role="status">{message}</p><form onSubmit={verify}><label>Код MFA<input autoFocus inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required value={code} onChange={e=>setCode(e.target.value)}/></label><button type="submit">Открыть короткую сессию</button></form></main>;
  return <main className="page control-page"><header><h1>LangTutor Control</h1><p role="status">{message}</p><button onClick={()=>void load()}>Обновить</button></header><section aria-labelledby="overview-title"><h2 id="overview-title">Сводка</h2><dl className="control-metrics">{Object.entries(overview).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></section><section aria-labelledby="reauth-title"><h2 id="reauth-title">Подтверждение опасных действий</h2><form onSubmit={reauth}><label>Пароль<input type="password" autoComplete="current-password" required minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Новый код MFA<input inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value)}/></label><button type="submit">Подтвердить на 2 минуты</button></form><label>Обязательная причина действия<input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label></section><section><h2>Пользователи</h2><div className="table-scroll"><table><thead><tr><th>Email</th><th>Статус</th><th>Семья</th><th>Токены</th><th>Действие</th></tr></thead><tbody>{users.map(user=><tr key={user.user_id}><td>{user.email}<br/><small>{user.display_name}</small></td><td>{user.status}{user.is_super_admin?" · admin":""}</td><td>{user.family_role??"—"}</td><td>{user.tokens_this_month}</td><td><button disabled={user.is_super_admin||reason.length<5} onClick={()=>void block(user)}>{user.status==="blocked"?"Разблокировать":"Заблокировать"}</button></td></tr>)}</tbody></table></div></section><section><h2>Семьи</h2><ul>{families.map(family=><li key={family.family_id}>{family.name}: {family.member_count} участников, {family.tokens_this_month} токенов</li>)}</ul></section><section><h2>AI-модели</h2><ul>{models.map(model=><li key={model.id}><code>{model.key}</code> — {model.enabled?"включена":"выключена"} <button disabled={reason.length<5} onClick={()=>void toggleModel(model)}>{model.enabled?"Выключить":"Включить"}</button></li>)}</ul></section><section><h2>Security events</h2>{events.length?<ul>{events.map((event,index)=><li key={`${event.created_at}-${index}`}>{event.severity}: {event.code} · {new Date(event.created_at).toLocaleString("ru")}</li>)}</ul>:<p>Событий нет</p>}</section></main>;
}
