import { FormEvent, useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Check, ChevronLeft, Headphones, Mic, Plus, Volume2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { BrowserSpeechRecognitionProvider, tts } from "../lib/speech";

type Word = { target: string; source: string; example: string; hint: string };
type Lesson = { lesson_key: string; title: string; position: number; content: { goal: string; minutes: number; explanation: string; practices: string[]; words: Word[] } };
type Course = { key: string; name: string; language_name: string; language_key: string; metadata?: { targetLocale?: string }; course_version_id: string; lessons: Lesson[] };
type Progress = { course_version_id: string; lesson_key: string; current_step: number; completion_percent: number; completed: boolean; score: number | null; version: number };
type Attempt = { score: number; correct: boolean; feedback: string };

async function request<T>(path: string, init?: RequestInit) {
  const response = await fetch(`/api/v1/learning${path}`, { credentials: "include", headers: { "Content-Type": "application/json" }, ...init });
  const body = await response.json();
  if (!response.ok) throw new Error(body?.error?.message ?? "Не удалось сохранить учебный результат");
  return body as T;
}
function speak(text: string, lang = "it-IT", rate = 0.9) { return tts.speak(text, { lang, rate }).catch(() => undefined); }
function useCourse(courseKey: string) {
  const course = useQuery({ queryKey: ["internet-course", courseKey], queryFn: () => request<Course>(`/courses/${courseKey}`), enabled: Boolean(courseKey) });
  const progress = useQuery({ queryKey: ["internet-progress"], queryFn: () => request<{ lessons: Progress[] }>("/progress") });
  return { course, progress };
}

export function InternetCoursePage() {
  const { courseKey = "" } = useParams();
  const { course, progress } = useCourse(courseKey);
  if (course.isLoading || progress.isLoading) return <section className="page"><h1>Курс</h1><p role="status">Загружаем уроки и прогресс…</p></section>;
  if (!course.data) return <section className="page"><h1>Курс недоступен</h1><Link className="button primary" to="/programs">К программам</Link></section>;
  const records = (progress.data?.lessons ?? []).filter((item) => item.course_version_id === course.data.course_version_id);
  return <section className="page"><p className="eyebrow">{course.data.language_name} · ПРОГРАММА A0–A1</p><h1>{course.data.name}</h1><p className="lead">Каждый урок: карточки и объяснение, аудирование, произношение и итоговая проверка.</p><div className="lesson-list">{course.data.lessons.map((lesson) => { const saved = records.find((item) => item.lesson_key === lesson.lesson_key); return <article className="lesson-card" key={lesson.lesson_key}><span className="lesson-number">{lesson.position}</span><div><p className="meta">{lesson.content.minutes} МИН · {lesson.content.words.length} СЛОВ</p><h2>{lesson.title}</h2><p>{lesson.content.goal}</p><div className="tags">{lesson.content.practices.map((practice) => <span key={practice}>{practice}</span>)}</div><div className="progress-line"><i style={{ width: `${saved?.completion_percent ?? 0}%` }} /></div></div><Link className="button secondary" to={`/programs/${courseKey}/lessons/${lesson.lesson_key}`}>{saved?.completed ? "Повторить" : saved ? "Продолжить" : "Начать"} <ArrowRight /></Link></article>; })}</div></section>;
}

type Stage = "cards" | "listening" | "pronunciation" | "quiz";
const stageLabels: Array<[Stage, string]> = [["cards", "Карточки"], ["listening", "Аудирование"], ["pronunciation", "Произношение"], ["quiz", "Проверка"]];

export function InternetLessonPage() {
  const { courseKey = "", lessonKey = "" } = useParams();
  const queryClient = useQueryClient(), { course, progress } = useCourse(courseKey);
  const [stage, setStage] = useState<Stage>("cards"), [index, setIndex] = useState(0), [show, setShow] = useState(false);
  const [answer, setAnswer] = useState(""), [feedback, setFeedback] = useState(""), [busy, setBusy] = useState(false), [quizPoints, setQuizPoints] = useState(0);
  const [localVersion, setLocalVersion] = useState<number | null>(null), recognition = useMemo(() => new BrowserSpeechRecognitionProvider(), []), [listening, setListening] = useState(false);
  useEffect(() => () => recognition.dispose(), [recognition]);
  const lesson = course.data?.lessons.find((item) => item.lesson_key === lessonKey);
  const record = progress.data?.lessons.find((item) => item.course_version_id === course.data?.course_version_id && item.lesson_key === lessonKey);
  useEffect(() => { if (record && localVersion === null) { setLocalVersion(record.version); setIndex(Math.min(record.current_step, Math.max((lesson?.content.words.length ?? 1) - 1, 0))); } }, [lesson?.content.words.length, localVersion, record]);
  if (course.isLoading || progress.isLoading) return <section className="page"><h1>Урок</h1><p role="status">Готовим урок…</p></section>;
  if (!course.data || !lesson) return <section className="page"><h1>Урок не найден</h1><Link to={`/programs/${courseKey}`}>Вернуться к программе</Link></section>;
  const words = lesson.content.words, word = words[index], targetLocale = course.data.metadata?.targetLocale ?? (course.data.language_key === "it" ? "it-IT" : "en-GB");
  async function saveProgress(completionPercent: number, completed = false, step = index) { const saved = await request<Progress>("/progress", { method: "PUT", body: JSON.stringify({ courseKey, lessonKey, currentStep: step, completionPercent, completed, version: localVersion ?? record?.version ?? 0 }) }); setLocalVersion(saved.version); await queryClient.invalidateQueries({ queryKey: ["internet-progress"] }); }
  async function addWord() { setBusy(true); try { await request("/vocabulary", { method: "POST", body: JSON.stringify({ courseKey, lessonKey, term: word.target, translation: word.source }) }); setFeedback(`«${word.target}» добавлено в «Мои слова».`); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function nextCard() { const next = Math.min(index + 1, words.length - 1); setBusy(true); try { await saveProgress(Math.round(((next + 1) / words.length) * 60), false, next); if (index === words.length - 1) { setStage("listening"); setIndex(0); } else setIndex(next); setShow(false); setAnswer(""); setFeedback(""); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function submitAttempt(value: string) { return request<Attempt>("/attempts", { method: "POST", body: JSON.stringify({ courseKey, lessonKey, exerciseKey: `word-${index + 1}`, answer: value }) }); }
  async function checkListening() { if (busy || !answer || feedback.startsWith("Верно")) return; setBusy(true); try { const result = await submitAttempt(answer); setFeedback(result.correct ? "Верно — вы узнали фразу на слух." : "Пока неверно. Выберите другой вариант и проверьте ещё раз."); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function checkPronunciation(event: FormEvent) { event.preventDefault(); if (!answer.trim()) return; setBusy(true); try { const result = await submitAttempt(answer); setFeedback(`${result.feedback}. Результат: ${result.score} из 100.`); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function toggleMic() { if (listening) { const result = await recognition.stop(); setListening(false); if (result.transcript) setAnswer(result.transcript); return; } if (!recognition.isAvailable()) { setFeedback("Голосовой ввод недоступен. Используйте Chrome или Edge и разрешите микрофон."); return; } try { setListening(true); setFeedback("Слушаю…"); await recognition.start({ onInterim: setAnswer, onFinal: setAnswer, onEnd: (value) => { setListening(false); if (value) { setAnswer(value); setFeedback("Фраза распознана — нажмите «Проверить»."); } }, onError: () => { setListening(false); setFeedback("Не удалось распознать речь. Проверьте разрешение на микрофон."); } }); } catch { setListening(false); setFeedback("Не удалось включить микрофон."); } }
  function advancePractice(nextStage: Stage) { const atEnd = index === words.length - 1; setFeedback(""); setAnswer(""); setIndex(atEnd ? 0 : index + 1); if (atEnd) setStage(nextStage); }
  async function checkQuiz(event: FormEvent) { event.preventDefault(); if (!answer.trim()) return; setBusy(true); try { const result = await submitAttempt(answer); setQuizPoints((value) => value + result.score); setFeedback(`${result.feedback}. ${result.score} из 100.`); if (index === Math.min(words.length, 5) - 1) await saveProgress(100, true, words.length); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  const changeStage = (value: Stage) => { setStage(value); setIndex(0); setAnswer(""); setFeedback(""); };
  const nav = <div className="training-modes" aria-label="Этапы урока">{stageLabels.map(([value, label]) => <button key={value} className={stage === value ? "selected" : ""} aria-pressed={stage === value} onClick={() => changeStage(value)}><b>{label}</b></button>)}</div>;
  if (stage === "cards") return <section className="page"><p className="eyebrow">УРОК {lesson.position} · {lesson.content.minutes} МИНУТ</p><h1>{lesson.title}</h1>{nav}<div className="lesson-layout"><article className="word-card"><div className="step"><span>Карточка {index + 1} из {words.length}</span><b>{Math.round(((index + 1) / words.length) * 100)}%</b></div><div className="bar"><i style={{ width: `${((index + 1) / words.length) * 100}%` }} /></div><p className="meta">{course.data.language_name}</p><h2 lang={course.data.language_key}>{word.target}</h2><button className="audio" onClick={() => void speak(word.target, targetLocale)}><Volume2 /> 1×</button><button className="audio" onClick={() => void speak(word.target, targetLocale, 0.72)}><Volume2 /> 0,75×</button><button className="reveal" onClick={() => setShow((value) => !value)}>{show ? "Скрыть перевод" : "Показать перевод"}</button>{show && <div className="translation"><b>{word.source}</b><p>{word.example}</p><small>{word.hint}</small><button className="button ghost" onClick={() => void speak(word.example, targetLocale, 0.82)}>Прослушать пример</button></div>}<div className="row wrap"><button className="button ghost" disabled={index === 0 || busy} onClick={() => { setIndex((value) => value - 1); setShow(false); }}><ChevronLeft /> Назад</button><button className="button ghost" disabled={busy} onClick={() => void addWord()}><Plus /> В словарь</button><button className="button secondary" disabled={busy} onClick={() => void nextCard()}>Знаю <Check /></button></div><p role="status">{feedback}</p></article><aside className="explain"><h3>Без сложных терминов</h3><p>{lesson.content.explanation}</p><h3>Дальше в уроке</h3><button onClick={() => changeStage("listening")}><Headphones /> Аудирование</button><button onClick={() => changeStage("pronunciation")}><Mic /> Произношение</button><button onClick={() => changeStage("quiz")}>Итоговая проверка <ArrowRight /></button></aside></div></section>;
  if (stage === "listening") { const alternatives = [word.target, words[(index + 2) % words.length].target, words[(index + 4) % words.length].target].sort((a, b) => a.localeCompare(b)), correct = feedback.startsWith("Верно"); return <section className="page"><p className="eyebrow">АУДИРОВАНИЕ · УРОК {lesson.position}</p><h1>Слушаем: {lesson.title}</h1>{nav}<article className="practice"><button className="listen" onClick={() => void speak(word.target, targetLocale, 0.82)}><Volume2 /> Прослушать</button><fieldset disabled={busy || correct}><legend>Что вы услышали?</legend>{alternatives.map((value) => <label className="option" key={value}><input type="radio" name="listening" checked={answer === value} onChange={() => { setAnswer(value); setFeedback(""); }} />{value}</label>)}</fieldset><button className="button secondary" disabled={!answer || busy || correct} onClick={() => void checkListening()}>Проверить ответ</button><p className={correct ? "feedback success" : "feedback"} role="status">{feedback}</p>{correct && <button className="button primary" onClick={() => advancePractice("pronunciation")}>Дальше <ArrowRight /></button>}</article></section>; }
  if (stage === "pronunciation") return <section className="page"><p className="eyebrow">ПРОИЗНОШЕНИЕ · УРОК {lesson.position}</p><h1>Говорим: {lesson.title}</h1>{nav}<article className="practice"><p className="target" lang={course.data.language_key}>{word.target}</p><button className="audio" onClick={() => void speak(word.target, targetLocale, 0.8)}><Volume2 /> Послушать образец</button><form onSubmit={checkPronunciation}><label>Распознанная фраза<input value={answer} onChange={(event) => setAnswer(event.target.value)} required /></label><div className="row wrap"><button type="button" className={listening ? "mic-button recording" : "mic-button"} onClick={() => void toggleMic()}><Mic /> {listening ? "Остановить" : "Произнести"}</button><button className="button primary" disabled={busy}>Проверить</button></div></form><p className="feedback" role="status">{feedback}</p>{feedback && !listening && <button className="button secondary" onClick={() => advancePractice("quiz")}>Следующая фраза</button>}</article></section>;
  const quizLength = Math.min(words.length, 5), lastQuestion = index === quizLength - 1;
  return <section className="page"><p className="eyebrow">ИТОГОВАЯ ПРОВЕРКА · УРОК {lesson.position}</p><h1>{lesson.title}</h1>{nav}<article className="quiz"><div className="step"><span>Вопрос {index + 1} из {quizLength}</span><b>{quizPoints} баллов</b></div><p className="target">{word.source}</p><form onSubmit={checkQuiz}><label>Переведите на {course.data.language_name.toLowerCase()}<input value={answer} onChange={(event) => setAnswer(event.target.value)} required /></label><button className="button primary" disabled={busy || Boolean(feedback)}>Проверить</button></form><p className="feedback" role="status">{feedback}</p>{feedback && (!lastQuestion ? <button className="button secondary" onClick={() => { setIndex((value) => value + 1); setAnswer(""); setFeedback(""); }}>Следующий вопрос</button> : <div><h2>Урок завершён</h2><p>{quizPoints + (feedback.includes("100 из 100") ? 100 : 0)} из {quizLength * 100} баллов</p><Link className="button primary" to={`/programs/${courseKey}`}>К списку уроков</Link></div>)}</article></section>;
}
