import {useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";

type Course={key:string;name:string;version:number;program_key:string;program_name:string;language_key:string;language_name:string;lesson_count:number;metadata:{cefr?:string[]};program_metadata:{prerequisites?:string[];skills?:string[]}};
const request=async<T,>(path:string,init?:RequestInit)=>{const response=await fetch(`/api/v1/learning${path}`,{credentials:"include",headers:{"content-type":"application/json"},...init});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message??"Не удалось загрузить программы");return body as T;};
export function ProgramsPage(){const client=useQueryClient(),[status,setStatus]=useState("Выберите программу обучения"),catalog=useQuery({queryKey:["internet-programs"],queryFn:()=>request<{courses:Course[]}>("/catalog")}),enroll=useMutation({mutationFn:(courseKey:string)=>request("/enrollments",{method:"POST",body:JSON.stringify({courseKey})}),onSuccess:async()=>{setStatus("Программа выбрана. Прогресс будет храниться в вашем аккаунте.");await client.invalidateQueries({queryKey:["internet-progress"]});},onError:error=>setStatus((error as Error).message)});
  if(catalog.isLoading)return <section className="page"><h1>Учебные программы</h1><p role="status">Загружаем каталог…</p></section>;if(catalog.error)return <section className="page"><h1>Учебные программы</h1><p role="alert">{catalog.error.message}. Войдите в интернет-аккаунт на странице авторизации.</p></section>;
  const grouped=(catalog.data?.courses??[]).reduce<Map<string,Course[]>>((result,course)=>{result.set(course.language_name,[...(result.get(course.language_name)??[]),course]);return result;},new Map());return <section className="page programs-page"><h1>Учебные программы</h1><p role="status">{status}</p>{[...grouped].map(([language,courses])=><section key={language} aria-labelledby={`language-${courses[0].language_key}`}><h2 id={`language-${courses[0].language_key}`}>{language}</h2><div className="program-grid">{courses.map(course=><article key={course.key}><h3>{course.name}</h3><p>{course.program_name}</p><p>Уроков: {course.lesson_count} · версия {course.version}{course.metadata.cefr?.length?` · ${course.metadata.cefr.join("–")}`:""}</p>{course.program_metadata.prerequisites?.length?<p>Рекомендуется: {course.program_metadata.prerequisites.join(", ")}</p>:null}<button disabled={enroll.isPending} onClick={()=>enroll.mutate(course.key)}>Выбрать программу</button></article>)}</div></section>)}</section>;
}
