import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import type pg from "pg";

type Counts={progress:number;attempts:number;vocabulary:number};
function stableUuid(value:string){const hex=crypto.createHash("sha256").update(`legacy:${value}`).digest("hex").slice(0,32).split("");hex[12]="5";hex[16]="8";const x=hex.join("");return`${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`;}
function fingerprint(file:string){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}

export async function importItalianLearent(options:{sqlitePath:string;legacyAnonymousId:string;userId:string;pool:pg.Pool;backupDirectory:string}){
  const source=path.resolve(options.sqlitePath),backupDirectory=path.resolve(options.backupDirectory);if(!fs.existsSync(source))throw new Error("SQLITE_SOURCE_NOT_FOUND");fs.mkdirSync(backupDirectory,{recursive:true});
  const db=new DatabaseSync(source);const integrity=(db.prepare("PRAGMA integrity_check").get() as{integrity_check:string}).integrity_check;if(integrity!=="ok"){db.close();throw new Error("SQLITE_INTEGRITY_FAILED");}db.prepare("PRAGMA wal_checkpoint(FULL)").get();
  const sourceFingerprint=fingerprint(source),backup=path.join(backupDirectory,`italianlearent-${sourceFingerprint.slice(0,12)}.sqlite`);if(!fs.existsSync(backup))fs.copyFileSync(source,backup);const backupDb=new DatabaseSync(backup,{readOnly:true});const backupIntegrity=(backupDb.prepare("PRAGMA integrity_check").get() as{integrity_check:string}).integrity_check;backupDb.close();if(backupIntegrity!=="ok"){db.close();throw new Error("SQLITE_BACKUP_INVALID");}
  const profile=db.prepare("SELECT id FROM profiles WHERE anonymous_id=?").get(options.legacyAnonymousId) as{id:string}|undefined;if(!profile){db.close();throw new Error("LEGACY_PROFILE_NOT_FOUND");}
  const progress=db.prepare("SELECT lesson_id,current_step,completion_percent,completed,score FROM lesson_progress WHERE profile_id=?").all(profile.id) as any[];
  const attempts=db.prepare("SELECT id,lesson_id,exercise_id,skill_type,score,feedback,created_at FROM skill_attempts WHERE profile_id=?").all(profile.id) as any[];
  const words=db.prepare("SELECT id,italian,translation,example_italian,example_russian,lesson_id,status,interval_days,repetitions,correct_count,error_count,next_review_at,created_at,updated_at FROM user_words WHERE profile_id=?").all(profile.id) as any[];db.close();
  const expected:Counts={progress:progress.length,attempts:attempts.length,vocabulary:words.length},client=await options.pool.connect();
  try{await client.query("BEGIN");await client.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id','',true)",[options.userId]);const previous=await client.query<{counts:Counts}>("SELECT counts FROM learning.legacy_imports WHERE user_id=$1 AND source_fingerprint=$2",[options.userId,sourceFingerprint]);if(previous.rows[0]){await client.query("ROLLBACK");return{status:"already_imported" as const,counts:previous.rows[0].counts,backup};}
    const course=await client.query("SELECT c.id course_id,cv.id version_id FROM learning.courses c JOIN learning.course_versions cv ON cv.course_id=c.id WHERE c.key='italian-a0-a1' AND cv.status='published' ORDER BY cv.version DESC LIMIT 1");if(!course.rows[0])throw new Error("COURSE_NOT_FOUND");const{course_id,version_id}=course.rows[0];
    await client.query("INSERT INTO learning.legacy_profile_links(user_id,legacy_anonymous_id) VALUES($1,$2)",[options.userId,options.legacyAnonymousId]);await client.query("INSERT INTO learning.course_enrollments(id,user_id,course_id,course_version_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,course_id) DO NOTHING",[stableUuid(`${options.userId}:enrollment`),options.userId,course_id,version_id]);
    for(const row of progress)await client.query("INSERT INTO learning.lesson_progress(id,user_id,course_id,course_version_id,lesson_key,current_step,completion_percent,completed,score) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(user_id,course_id,lesson_key) DO UPDATE SET current_step=GREATEST(learning.lesson_progress.current_step,excluded.current_step),completion_percent=GREATEST(learning.lesson_progress.completion_percent,excluded.completion_percent),completed=learning.lesson_progress.completed OR excluded.completed,score=GREATEST(learning.lesson_progress.score,excluded.score),updated_at=now()",[stableUuid(`progress:${row.lesson_id}:${options.legacyAnonymousId}`),options.userId,course_id,version_id,row.lesson_id,row.current_step,row.completion_percent,Boolean(row.completed),row.score]);
    for(const row of attempts)await client.query("INSERT INTO learning.exercise_attempts(id,user_id,course_id,course_version_id,lesson_key,exercise_key,skill_type,score,feedback,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO NOTHING",[stableUuid(`attempt:${row.id}`),options.userId,course_id,version_id,row.lesson_id??"legacy",row.exercise_id,row.skill_type,row.score,row.feedback,row.created_at]);
    for(const row of words){const id=stableUuid(`word:${row.id}`);await client.query("INSERT INTO learning.vocabulary_items(id,user_id,course_id,term,translation,example_target,example_source,lesson_key,status,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(user_id,course_id,term) DO UPDATE SET translation=excluded.translation",[id,options.userId,course_id,row.italian,row.translation,row.example_italian,row.example_russian,row.lesson_id,row.status,row.created_at,row.updated_at]);await client.query("INSERT INTO learning.review_schedule(vocabulary_id,user_id,interval_days,repetitions,correct_count,error_count,next_review_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(vocabulary_id) DO UPDATE SET interval_days=GREATEST(learning.review_schedule.interval_days,excluded.interval_days),repetitions=GREATEST(learning.review_schedule.repetitions,excluded.repetitions),correct_count=GREATEST(learning.review_schedule.correct_count,excluded.correct_count),error_count=GREATEST(learning.review_schedule.error_count,excluded.error_count),next_review_at=GREATEST(learning.review_schedule.next_review_at,excluded.next_review_at)",[id,options.userId,row.interval_days,row.repetitions,row.correct_count,row.error_count,row.next_review_at]);}
    const actual={progress:Number((await client.query("SELECT count(*) n FROM learning.lesson_progress WHERE user_id=$1 AND course_id=$2",[options.userId,course_id])).rows[0].n),attempts:Number((await client.query("SELECT count(*) n FROM learning.exercise_attempts WHERE user_id=$1 AND course_id=$2",[options.userId,course_id])).rows[0].n),vocabulary:Number((await client.query("SELECT count(*) n FROM learning.vocabulary_items WHERE user_id=$1 AND course_id=$2",[options.userId,course_id])).rows[0].n)};if(actual.progress<expected.progress||actual.attempts<expected.attempts||actual.vocabulary<expected.vocabulary)throw new Error("IMPORT_PARITY_FAILED");await client.query("INSERT INTO learning.legacy_imports(id,user_id,source_fingerprint,status,counts) VALUES($1,$2,$3,'completed',$4::jsonb)",[crypto.randomUUID(),options.userId,sourceFingerprint,JSON.stringify(actual)]);await client.query("COMMIT");return{status:"imported" as const,counts:actual,sourceCounts:expected,backup};
  }catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}
