import crypto from "node:crypto";
import type pg from "pg";

export class LearningService {
  constructor(private readonly pool:pg.Pool){}
  async catalog(){return (await this.pool.query("SELECT c.key,c.name,c.metadata,cv.version,cv.id course_version_id,p.key program_key,p.name program_name,p.metadata program_metadata,l.key language_key,l.name language_name,(SELECT count(*)::int FROM learning.lessons x WHERE x.course_version_id=cv.id) lesson_count FROM learning.courses c JOIN learning.programs p ON p.id=c.program_id JOIN learning.languages l ON l.id=p.language_id JOIN learning.course_versions cv ON cv.course_id=c.id WHERE cv.status='published' ORDER BY l.key,p.key,c.key")).rows;}
  async course(courseKey:string){const course=await this.pool.query("SELECT c.key,c.name,c.metadata,cv.version,cv.id course_version_id,p.key program_key,p.name program_name,p.metadata program_metadata,l.key language_key,l.name language_name FROM learning.courses c JOIN learning.programs p ON p.id=c.program_id JOIN learning.languages l ON l.id=p.language_id JOIN learning.course_versions cv ON cv.course_id=c.id WHERE c.key=$1 AND cv.status='published' ORDER BY cv.version DESC LIMIT 1",[courseKey]);if(!course.rows[0])throw new Error("COURSE_NOT_FOUND");const lessons=await this.pool.query("SELECT lesson_key,title,position,content FROM learning.lessons WHERE course_version_id=$1 ORDER BY position",[course.rows[0].course_version_id]);return{...course.rows[0],lessons:lessons.rows};}
  async enroll(userId:string,familyId:string|null,courseKey:string){return this.tx(userId,familyId,async c=>{const course=await c.query("SELECT c.id course_id,cv.id version_id FROM learning.courses c JOIN learning.course_versions cv ON cv.course_id=c.id WHERE c.key=$1 AND cv.status='published' ORDER BY cv.version DESC LIMIT 1",[courseKey]);if(!course.rows[0])throw new Error("COURSE_NOT_FOUND");const id=crypto.randomUUID();const result=await c.query("INSERT INTO learning.course_enrollments(id,user_id,course_id,course_version_id) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,course_id) DO UPDATE SET status='active' RETURNING id,course_id,course_version_id,status",[id,userId,course.rows[0].course_id,course.rows[0].version_id]);return result.rows[0];});}
  async enrollments(userId:string,familyId:string|null){return this.tx(userId,familyId,async c=>(await c.query("SELECT e.id,c.key course_key,c.name course_name,l.key language_key,l.name language_name,e.status,e.enrolled_at FROM learning.course_enrollments e JOIN learning.courses c ON c.id=e.course_id JOIN learning.programs p ON p.id=c.program_id JOIN learning.languages l ON l.id=p.language_id WHERE e.user_id=$1 AND e.status='active' ORDER BY e.enrolled_at",[userId])).rows);}
  async settings(userId:string,familyId:string|null){return this.tx(userId,familyId,async c=>(await c.query("SELECT values,version,updated_at FROM learning.user_learning_settings WHERE user_id=$1",[userId])).rows[0]??{values:{},version:0});}
  async saveSettings(userId:string,familyId:string|null,values:Record<string,unknown>){return this.tx(userId,familyId,async c=>(await c.query("INSERT INTO learning.user_learning_settings(user_id,values) VALUES($1,$2::jsonb) ON CONFLICT(user_id) DO UPDATE SET values=learning.user_learning_settings.values||excluded.values,version=learning.user_learning_settings.version+1,updated_at=now() RETURNING values,version,updated_at",[userId,JSON.stringify(values)])).rows[0]);}
  async progress(userId:string,familyId:string|null){return this.tx(userId,familyId,async c=>(await c.query("SELECT course_id,course_version_id,lesson_key,current_step,completion_percent,completed,score,version,updated_at FROM learning.lesson_progress WHERE user_id=$1 ORDER BY updated_at",[userId])).rows);}
  async saveProgress(userId:string,familyId:string|null,input:{courseKey:string;lessonKey:string;currentStep:number;completionPercent:number;completed:boolean;version:number}){return this.tx(userId,familyId,async c=>{const enrollment=await this.enrollment(c,userId,input.courseKey);const existing=await c.query<{version:number}>("SELECT version FROM learning.lesson_progress WHERE user_id=$1 AND course_id=$2 AND lesson_key=$3",[userId,enrollment.course_id,input.lessonKey]);if(existing.rows[0]&&existing.rows[0].version!==input.version)throw new Error("VERSION_CONFLICT");const result=await c.query("INSERT INTO learning.lesson_progress(id,user_id,course_id,course_version_id,lesson_key,current_step,completion_percent,completed,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,1) ON CONFLICT(user_id,course_id,lesson_key) DO UPDATE SET current_step=excluded.current_step,completion_percent=excluded.completion_percent,completed=excluded.completed,version=learning.lesson_progress.version+1,updated_at=now() RETURNING lesson_key,current_step,completion_percent,completed,version",[crypto.randomUUID(),userId,enrollment.course_id,enrollment.course_version_id,input.lessonKey,input.currentStep,input.completionPercent,input.completed]);return result.rows[0];});}
  async submitAttempt(userId:string,familyId:string|null,input:{courseKey:string;lessonKey:string;exerciseKey:string;answer:string}){return this.tx(userId,familyId,async c=>{const enrollment=await this.enrollment(c,userId,input.courseKey);const exercise=await c.query<{content:{expectedAnswer?:string;skillType?:string}}>("SELECT e.content FROM learning.exercises e JOIN learning.lessons l ON l.id=e.lesson_id WHERE l.course_version_id=$1 AND l.lesson_key=$2 AND e.exercise_key=$3",[enrollment.course_version_id,input.lessonKey,input.exerciseKey]);const expected=exercise.rows[0]?.content.expectedAnswer;if(!expected)throw new Error("EXERCISE_NOT_SCORABLE");const normalize=(value:string)=>value.toLocaleLowerCase("it").replace(/[.!?,'’]/g,"").replace(/\s+/g," ").trim();const score=normalize(expected)===normalize(input.answer)?100:0;await c.query("INSERT INTO learning.exercise_attempts(id,user_id,course_id,course_version_id,lesson_key,exercise_key,skill_type,score,feedback) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[crypto.randomUUID(),userId,enrollment.course_id,enrollment.course_version_id,input.lessonKey,input.exerciseKey,exercise.rows[0].content.skillType??"vocabulary",score,score===100?"Верно":"Повторите слово"]);return{score,correct:score===100,feedback:score===100?"Верно":"Повторите слово"};});}
  async addVocabulary(userId:string,familyId:string|null,input:{courseKey:string;term:string;translation:string;lessonKey?:string}){return this.tx(userId,familyId,async c=>{const enrollment=await this.enrollment(c,userId,input.courseKey),id=crypto.randomUUID();const row=await c.query("INSERT INTO learning.vocabulary_items(id,user_id,course_id,term,translation,lesson_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,course_id,term) DO UPDATE SET translation=excluded.translation,lesson_key=excluded.lesson_key,updated_at=now() RETURNING id,term,translation,status",[id,userId,enrollment.course_id,input.term,input.translation,input.lessonKey??null]);await c.query("INSERT INTO learning.review_schedule(vocabulary_id,user_id,next_review_at) VALUES($1,$2,now()+interval '1 day') ON CONFLICT(vocabulary_id) DO NOTHING",[row.rows[0].id,userId]);return row.rows[0];});}
  private async enrollment(c:pg.PoolClient,userId:string,courseKey:string){const r=await c.query("SELECT e.course_id,e.course_version_id FROM learning.course_enrollments e JOIN learning.courses c ON c.id=e.course_id WHERE e.user_id=$1 AND c.key=$2 AND e.status='active'",[userId,courseKey]);if(!r.rows[0])throw new Error("ENROLLMENT_REQUIRED");return r.rows[0];}
  private async tx<T>(userId:string,familyId:string|null,fn:(c:pg.PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query("BEGIN");await c.query("SELECT set_config('app.user_id',$1,true),set_config('app.family_id',$2,true)",[userId,familyId??""]);const result=await fn(c);await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
}
